#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack   ###################
##################################################
## workaround to include linaro tests
## http://android-review.linaro.org/c/device/ti/am65xevm/+/20366
apply --linaro device/ti/am65xevm 20366/1

## workaround for compiling kernel
## http://android-review.linaro.org/c/device/ti/am65xevm/+/20344
apply --linaro device/ti/am65xevm 20344/4

## bootloaders.mk: workaround to build firmwares for am65x
## http://android-review.linaro.org/c/device/ti/am65xevm/+/20376
apply --linaro device/ti/am65xevm 20376/2
