#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
	AOSP="$1"
else
	AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
	echo "This script must be run from the AOSP source directory"
	echo "or with the AOSP source directory as its first parameter."
	exit 1
fi

init

#============================================
# Patches needed to make it build with clang
#============================================
# Don't #define snprintf
# https://android-review.googlesource.com/#/c/109026/
apply bionic 109026/1

# Bluedroid cleanups
# https://android-review.googlesource.com/#/c/114282/
apply external/bluetooth/bluedroid 114282/1

# Overloaded virtual
# https://android-review.googlesource.com/#/c/109786/
apply frameworks/native 114876/1
# Remove unused function
# https://android-review.googlesource.com/#/c/109762/
#apply frameworks/base 109762/1

# __attribute__((__aligned__)) workaround
# https://android-review.googlesource.com/#/c/109567/
apply system/core 109567/2

# Fix checks for {Front,Side,Back}ElementIsCpe
# https://android-review.googlesource.com/#/c/109025/
apply external/aac 109025/3

# Check for condition that can't happen
# https://android-review.googlesource.com/#/c/109765/
apply hardware/invensense 109765/1

# Fix Nexus 10 build
# https://android-review.googlesource.com/#/c/110220/
apply hardware/samsung_slsi/exynos5 110220/2

# bogus overload
# https://android-review.googlesource.com/115615
apply frameworks/av 115615/1

# gcc pragmas
# https://android-review.googlesource.com/115662
apply frameworks/base 115662/2

# C++11 extensions in C++98 code
# https://android-review.googlesource.com/114951 --- ultimately to be replaced by 115674
apply frameworks/av 114951/1

# https://android-review.googlesource.com/114911
#apply frameworks/native 114911/1

# asm fixes
# https://android-review.googlesource.com/115660
# https://android-review.googlesource.com/#/c/116241
# 115660 breaks compatibility with gcc, but is the
# right thing to do once binutils is fixed.
#apply external/libhevc 115660/2
apply external/libhevc 116241/1

# Workaround for clang bug
# https://android-review.googlesource.com/115666
apply frameworks/av 115666/1

# Invalid assembly
# https://android-review.googlesource.com/114872
apply external/skia 114872/1

# https://android-review.googlesource.com/115884
apply frameworks/base 115884/1

# C++11 in C++98 mode
# https://android-review.googlesource.com/115876
apply hardware/ril 115876/1

echo "Applied $PATCHES patches"
