#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
	AOSP="$1"
else
	AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
	echo "This script must be run from the AOSP source directory"
	echo "or with the AOSP source directory as its first parameter."
	exit 1
fi

init

#============================================
# Patches needed to make it build with clang
#============================================
# Don't #define snprintf
# https://android-review.googlesource.com/#/c/109026/
apply bionic 109026/1

# Bluedroid cleanups
# https://android-review.googlesource.com/#/c/114282/
apply external/bluetooth/bluedroid 114282/2

# __attribute__((__aligned__)) workaround
# https://android-review.googlesource.com/#/c/109567/
apply system/core 109567/2

# Fix Nexus 10 build
# https://android-review.googlesource.com/#/c/110220/
apply hardware/samsung_slsi/exynos5 110220/2

# gcc pragmas
# https://android-review.googlesource.com/115662
apply frameworks/base 115662/2

# C++11 extensions in C++98 code
# https://android-review.googlesource.com/114951 --- ultimately to be replaced by 115674
apply frameworks/av 114951/1

# asm fixes
# https://android-review.googlesource.com/115660
apply external/libhevc 115660/6

# Workaround for clang bug
# https://android-review.googlesource.com/115666
apply frameworks/av 115666/1

# Invalid assembly
# https://android-review.googlesource.com/116718
apply external/skia 116718/1

# https://android-review.googlesource.com/115884
apply frameworks/base 115884/1

# Use of pldw without specifying target CPU
# https://android-review.googlesource.com/116773
apply bionic 116773/1

# C++11 in C++98 mode
# https://android-review.googlesource.com/115876
apply hardware/ril 115876/1

# Fixes needed only after C++11 switch
apply frameworks/av 116493/1
apply external/aac 116625/1
apply hardware/qcom/media 116672/1
apply hardware/qcom/media 116648/1

# 64-bit support
apply art 116717/1
apply frameworks/av 116770/1
apply frameworks/base 116780/2

echo "Applied $PATCHES patches"
