#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

# Include bionic tests patch http://review.android.git.linaro.org/#/c/15343/
apply --linaro system/extras 15343/1

# Allow skia to build with giflib5.1
apply external/skia 151010/1

# patch to integrate tjbench test on jpeg project   24
apply --linaro external/jpeg 15791/1
