#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

###################################################################
########              LKFT fixes for HiKey            #############
###################################################################
## https://android-review.googlesource.com/c/device/linaro/hikey/+/526099
apply --linaro device/linaro/hikey 18066/1
cherrypick frameworks/native c9d2db18d8154ef527dbf4d34c7bb3317bbdc98c
