#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
	AOSP="$1"
else
	AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
	echo "This script must be run from the AOSP source directory"
	echo "or with the AOSP source directory as its first parameter."
	exit 1
fi

init

#============================================
# Patches needed to make it build with clang
#============================================
# Fix Nexus 10 build
# https://android-review.googlesource.com/#/c/110220/
apply hardware/samsung_slsi/exynos5 110220/3

echo "Applied $PATCHES patches"
