#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

# Include bionic tests patch http://review.android.git.linaro.org/#/c/15343/
apply --linaro system/extras 15343/1

# Include fix for monkey crash on browser package:
# https://android-review.googlesource.com/#/c/116885/
apply packages/apps/Browser 116885/1

# Include patch for start and stop file path for bootchart:
# https://android-review.googlesource.com/#/c/117071/
apply system/core 117071/1
