#!/bin/bash

# this file should be placed last in the PATCHSETS list of
# android-build-configs
if [ -d "vendor/widevine" ]; then
	. build/envsetup.sh && mmma vendor/widevine
fi
if [ -d "external/optee-widevine-ref" ]; then
	external/optee-widevine-ref/build-exo.sh
fi
