#!/bin/bash

# this file should be placed last in the PATCHSETS list of
# android-build-configs

function export_config(){
	file=$1-optee-p-widevine
	echo "Exporting configs from android-build-configs/${file}"

	while read line; do
		if echo "${line}"|tr -d '[:blank:]'|grep -q '^$'; then
			continue
		fi
		if ! echo ${line} |grep -q '^#'; then
			echo "export ${line}"
			eval "export ${line}"
		fi
	done < android-build-configs/${file}
}

echo "Building ExoPlayer.."
if [ -f "external/optee-widevine-ref/build-exo.sh" ]; then
	external/optee-widevine-ref/build-exo.sh
	RESULT=$?
	if [ $RESULT -eq 0 ]; then
		if [ -d "optee/tools-images-hikey960" ]; then
			mkdir -p out/target/product/hikey960/system/priv-app/
			cp $(find ../ExoPlayer -name \*.apk) out/target/product/hikey960/system/priv-app/
		else
			mkdir -p out/target/product/hikey/system/priv-app/
			cp $(find ../ExoPlayer -name \*.apk) out/target/product/hikey/system/priv-app/
		fi
	fi
fi

# print newline for readability
echo

echo "Building liboemcrypto and related packages by calling"
echo "'lunch' and 'mmma vendor/widevine'"
echo
if [ -d "vendor/widevine" ]; then
	if [ -d "optee/tools-images-hikey960" ]; then
		export_config hikey960 && . build/envsetup.sh && lunch hikey960-userdebug && mmma vendor/widevine
	else
		export_config hikey && . build/envsetup.sh && lunch hikey-userdebug && mmma vendor/widevine
	fi
fi
