#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

####################################################################
############### Workarounds for using master clang  ################
####################################################################
#apply --linaro build/soong 18068/1
apply art 665201/1
apply system/libhidl 665202/2
apply system/libhwbinder 665203/1
apply system/netd 665204/1
apply system/tools/hidl 665221/1
apply system/vold 665205/1
