#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack   ###################
##################################################
## Linaro patch for development based on the AOSP master branch
## Set TARGET_CPU_VARIANT and TARGET_2ND_CPU_VARIANT,
## and integrated tests
## http://android-review.linaro.org/17155
apply --linaro art 17470/1
apply --linaro build/soong 17471/1
apply --linaro system/bt 17472/1
apply --linaro external/llvm 17473/1
apply --linaro frameworks/compile/slang 17474/1
apply --linaro frameworks/native 17475/1
apply --linaro system/netd 17476/1
apply --linaro frameworks/base 17477/1
