#!/bin/sh
wget https://dl.google.com/dl/android/aosp/asus-flo-lrx21p-4d3460bb.tgz
wget https://dl.google.com/dl/android/aosp/broadcom-flo-lrx21p-ed7aabcb.tgz
wget https://dl.google.com/dl/android/aosp/qcom-flo-lrx21p-294f38cd.tgz
for i in *-flo-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-flo.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-flo-*.tgz extract-*-flo.sh
