#!/bin/sh
# https://developers.google.com/android/nexus/blobs-preview
wget https://dl.google.com/dl/android/aosp/asus-flo-1718904-94213546.tgz
wget https://dl.google.com/dl/android/aosp/broadcom-flo-1718904-a2fee4c4.tgz
wget https://dl.google.com/dl/android/aosp/qcom-flo-1718904-f1c6bdc3.tgz
for i in *-flo-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-flo.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-flo-*.tgz extract-*-flo.sh
