#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/broadcom-shamu-lmy48i-9527e42c.tgz
wget https://dl.google.com/dl/android/aosp/moto-shamu-lmy48i-6a571991.tgz
wget https://dl.google.com/dl/android/aosp/qcom-shamu-lmy48i-6d0f48b2.tgz
for i in *-shamu-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-shamu.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-shamu-*.tgz extract-*-shamu.sh
