#!/bin/bash
# https://dl.google.com/dl/android/aosp/linaro-hikey-20170523-4b9ebaff.tgz
wget --no-check-certificate https://dl.google.com/dl/android/aosp/linaro-hikey-20170523-4b9ebaff.tgz
for i in linaro-hikey-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-linaro-hikey.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk linaro-hikey-*.tgz extract-linaro-hikey.sh
