#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/broadcom-shamu-mmb29s-faefff51.tgz
wget https://dl.google.com/dl/android/aosp/moto-shamu-mmb29s-62c5030c.tgz
wget https://dl.google.com/dl/android/aosp/qcom-shamu-mmb29s-1ae957bd.tgz
for i in *-shamu-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-shamu.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-shamu-*.tgz extract-*-shamu.sh
