#!/bin/sh
# https://developers.google.com/android/nexus/blobs-preview
wget https://dl.google.com/dl/android/aosp/broadcom-hammerhead-2129077-5bbe2bcf.tgz
wget https://dl.google.com/dl/android/aosp/lge-hammerhead-2129077-3ce6d4b5.tgz
wget https://dl.google.com/dl/android/aosp/qcom-hammerhead-2129077-679eae76.tgz
for i in *-hammerhead-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-hammerhead.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-hammerhead-*.tgz extract-*-hammerhead.sh
