#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/asus-flo-lmy48i-8146d0f6.tgz
wget https://dl.google.com/dl/android/aosp/broadcom-flo-lmy48i-908efbcf.tgz
wget https://dl.google.com/dl/android/aosp/qcom-flo-lmy48i-0e765cdb.tgz
for i in *-flo-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-flo.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-flo-*.tgz extract-*-flo.sh
