#!/bin/sh
# https://developers.google.com/android/nexus/blobs-preview
wget https://dl.google.com/dl/android/aosp/broadcom-mako-1632165-2c667b21.tgz
wget https://dl.google.com/dl/android/aosp/lge-mako-1632165-86576932.tgz
wget https://dl.google.com/dl/android/aosp/qcom-mako-1632165-609d4eb0.tgz
for i in *-mako-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-mako.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-mako-*.tgz extract-*-mako.sh
