#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/audience-manta-lrx22c-6a2c3d27.tgz
wget https://dl.google.com/dl/android/aosp/broadcom-manta-lrx22c-4cbf66a6.tgz
wget https://dl.google.com/dl/android/aosp/samsung-manta-lrx22c-73b9c3b2.tgz
for i in *-manta-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-manta.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-manta-*.tgz extract-*-manta.sh
