#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/asus-flo-mra58k-87448153.tgz
wget https://dl.google.com/dl/android/aosp/broadcom-flo-mra58k-b07af3c3.tgz
wget https://dl.google.com/dl/android/aosp/qcom-flo-mra58k-c1fa7908.tgz
for i in *-flo-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-flo.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-flo-*.tgz extract-*-flo.sh
