#!/bin/sh
# https://developers.google.com/android/nexus/blobs-preview
wget https://dl.google.com/dl/android/aosp/asus-flo-2129077-c5f26a4b.tgz
wget https://dl.google.com/dl/android/aosp/broadcom-flo-2129077-01fc5830.tgz
wget https://dl.google.com/dl/android/aosp/qcom-flo-2129077-8e693d41.tgz
for i in *-flo-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-flo.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-flo-*.tgz extract-*-flo.sh
