#!/bin/sh
# https://developers.google.com/android/nexus/blobs-preview
wget https://dl.google.com/dl/android/aosp/broadcom-hammerhead-1718904-a9c486c5.tgz
wget https://dl.google.com/dl/android/aosp/lge-hammerhead-1718904-2d2ad49f.tgz
wget https://dl.google.com/dl/android/aosp/qcom-hammerhead-1718904-d9c48efb.tgz
for i in *-hammerhead-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-hammerhead.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-hammerhead-*.tgz extract-*-hammerhead.sh
