#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/broadcom-mako-lmy48i-03207d49.tgz
wget https://dl.google.com/dl/android/aosp/lge-mako-lmy48i-8378a7ca.tgz
wget https://dl.google.com/dl/android/aosp/qcom-mako-lmy48i-9e546faa.tgz
for i in *-mako-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-mako.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-mako-*.tgz extract-*-mako.sh
