#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/audience-manta-lmy47v-c4c9b3f6.tgz
wget https://dl.google.com/dl/android/aosp/broadcom-manta-lmy47v-a74b784c.tgz
wget https://dl.google.com/dl/android/aosp/samsung-manta-lmy47v-cb388740.tgz
for i in *-manta-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-manta.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-manta-*.tgz extract-*-manta.sh
sed -i -e '/LOCAL_MODULE := libmalicore/iLOCAL_STRIP_MODULE := false' vendor/samsung/manta/proprietary/Android.mk
