#!/bin/sh
# https://developers.google.com/android/nexus/blobs-preview
wget https://dl.google.com/dl/android/aosp/broadcom-mako-2129077-63ab494e.tgz
wget https://dl.google.com/dl/android/aosp/lge-mako-2129077-8195b9ae.tgz
wget https://dl.google.com/dl/android/aosp/qcom-mako-2129077-b225071c.tgz
for i in *-mako-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-mako.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-mako-*.tgz extract-*-mako.sh
