#!/bin/sh
# https://developers.google.com/android/nexus/blobs-preview
wget https://dl.google.com/dl/android/aosp/broadcom-shamu-2129077-94dd9ecc.tgz
wget https://dl.google.com/dl/android/aosp/moto-shamu-2129077-f72c7387.tgz
wget https://dl.google.com/dl/android/aosp/qcom-shamu-2129077-f6c375aa.tgz
for i in *-shamu-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-shamu.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-shamu-*.tgz extract-*-shamu.sh
