#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/broadcom-mako-lmy48t-decb9f51.tgz
wget https://dl.google.com/dl/android/aosp/lge-mako-lmy48t-ff9ca8d1.tgz
wget https://dl.google.com/dl/android/aosp/qcom-mako-lmy48t-8c489b7e.tgz
for i in *-mako-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-mako.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-mako-*.tgz extract-*-mako.sh
