#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/broadcom-shamu-lrx22c-602f9b2e.tgz
wget https://dl.google.com/dl/android/aosp/moto-shamu-lrx22c-b19e597a.tgz
wget https://dl.google.com/dl/android/aosp/qcom-shamu-lrx22c-ddeee8d1.tgz
for i in *-hammerhead-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-hammerhead.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-hammerhead-*.tgz extract-*-hammerhead.sh
