#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/broadcom-hammerhead-lmy48i-6922f559.tgz
wget https://dl.google.com/dl/android/aosp/lge-hammerhead-lmy48i-42aa57af.tgz
wget https://dl.google.com/dl/android/aosp/qcom-hammerhead-lmy48i-b7faab74.tgz
for i in *-hammerhead-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-hammerhead.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-hammerhead-*.tgz extract-*-hammerhead.sh
