#!/bin/sh
# https://developers.google.com/android/nexus/blobs-preview
wget https://dl.google.com/dl/android/aosp/audience-manta-1718904-b4df207a.tgz
wget https://dl.google.com/dl/android/aosp/broadcom-manta-1718904-dc5de3e9.tgz
wget https://dl.google.com/dl/android/aosp/samsung-manta-1718904-c3840991.tgz
for i in *-manta-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-manta.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-manta-*.tgz extract-*-manta.sh
