#!/bin/sh
# https://developers.google.com/android/nexus/drivers
wget https://dl.google.com/dl/android/aosp/broadcom-mako-lrx22c-ea539f92.tgz
wget https://dl.google.com/dl/android/aosp/lge-mako-lrx22c-ad9be737.tgz
wget https://dl.google.com/dl/android/aosp/qcom-mako-lrx22c-1146e92c.tgz
for i in *-mako-*.tgz; do
	tar xf $i
done
mkdir junk
echo 'cat "$@"' >junk/more
chmod +x junk/more
export PATH=`pwd`/junk:$PATH
for i in extract-*-mako.sh; do
	echo -e "\nI ACCEPT" |./$i
done
rm -rf junk *-mako-*.tgz extract-*-mako.sh
