#!/bin/sh

. $(dirname $0)/functions

curl_am_hikey_optee(){
    local patch_id=$1
    local patch_url="https://git.linaro.org/kernel/linux-linaro-stable.git/patch/?id=${patch_id}"
    local patch_project="kernel/linaro/hisilicon"
    curl_am ${patch_url} ${patch_project}
}

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
###### OP-TEE support on device config        ####
##################################################
## Integrate OP-TEE components
## optee: integrate for optee components
## http://android-review.linaro.org/18142
apply --linaro device/linaro/hikey 18142/1

## OP-TEE selinux
## https://android-review.linaro.org/#/c/17177/
apply --linaro device/linaro/hikey 17177/10

## Enable OP-TEE in the bootloader
## https://android-review.linaro.org/#/c/18144/
apply --linaro device/linaro/hikey 18144/1
## build_uefi.mk: to build uefi files automatically when build android
## https://android-review.linaro.org/#/c/18145/
apply --linaro device/linaro/hikey 18145/1

## fix selinux policy for optee
## https://android-review.linaro.org/#/c/18062/
apply --linaro device/linaro/hikey 18062/1

## Android.mk: change to use OPTEE_BIN instead of BUILD_OPTEE_OS
cherrypick external/optee_test b31d4a96882bf0036e518c40500b35a788b0c120
## Android.mk: workaround missing-field-initializers error
cherrypick external/optee_test ea8378202c56b6163749bea575313c725322b874

## mk/aosp_optee.mk: define OPTEE_BIN for path of tee.bin
cherrypick optee/optee_os 2ef721a76a1a09ec8ec398aeee64449eb692dd91
## compiler.h: Avoid macro redefinition
cherrypick optee/optee_os decd9df74653f63131ae57fee191b91274f35d4e
