#!/bin/bash -e

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
##  workaround for linaro work                   ######
#######################################################
cd device/linaro/hikey
git pull https://android.googlesource.com/device/linaro/hikey refs/changes/59/727159/2
cd -

## domain.te: Add map permissions to vendor_config_files
## http://android-review.linaro.org/#/c/device/linaro/hikey/+/19582
apply --linaro device/linaro/hikey 19582/1

## sepolicy/vendor_init.te: Allow mmap for vendor_init
## http://android-review.linaro.org/#/c/device/linaro/hikey/+/19596
apply --linaro device/linaro/hikey 19596/1

## http://android-review.linaro.org/#/c/device/linaro/hikey/+/19677
## sepolicy/system_server.te: Explicitly allow system_server to (m)map data files
apply --linaro device/linaro/hikey 19677/1

## Relax some neverallow rules
## bd3e300a1309323e02c7144202acb48f40f11946
#cherrypick system/sepolicy bd3e300a1309323e02c7144202acb48f40f11946

## integrated tests
## http://android-review.linaro.org/17155
apply --linaro device/linaro/hikey 17155/8

## enabling kernel compilation, etc
## enable kernel compilation for hikey build
## http://android-review.linaro.org/18395
apply --linaro device/linaro/hikey 18395/4

## BoardConfigCommon.mk: update to build based on kernel hisilicon-4.14 path
## http://android-review.linaro.org/18465
apply --linaro device/linaro/hikey 18465/1

## drm/hisilicon: Ensure LDI regs are properly configured.
## commit a2f042430784d86eb2b7a6d2a869f552da30edba upstream.
revert kernel/linaro/hisilicon-4.14 f5e69000aa80880491ca4a613679bd21c60b048b

## For using drm_hwcomposer introduced by kernel change here:
## https://android-review.googlesource.com/c/kernel/hikey-linaro/+/743922
## hikey/hikey960: Enable drm_hwcomposer for 4.14+ kernels
## https://android-review.googlesource.com/c/device/linaro/hikey/+/737121
cherrypick device/linaro/hikey 6dc5ce5dbcd79e6fb6abb157e24b381d4f09d04a
## hikey: Enable drm_hwcomposer on 4.9 kernels
## https://android-review.googlesource.com/c/device/linaro/hikey/+/748113
cherrypick device/linaro/hikey 890bbe447ca065bd9d325d1fc14ceebd040b50a4
## hikey: gralloc: Change to allow gralloc_priv.h to be shared
cherrypick device/linaro/hikey 25d6129aed2ffa8a7d502c3703f82500ecc3a2ad
## hikey: gralloc: Add union alias and additional fields to improve interop w/ hikey960 gralloc
cherrypick device/linaro/hikey 30941517aac192a55dc358479e27dc6a6b3bc04e
## hikey: gralloc: Allow use of CMA heap instead of fbdev
cherrypick device/linaro/hikey f3d868dcbd74d43b754bf168fd5f63bf4c8c4385

## hikey{,960}: Enable system-as-root and verity.
cherrypick device/linaro/hikey 11c5e3e98827c301fc6a5364ae8b7dab93a22de4

## device-common.mk: set PRODUCT_SHIPPING_API_LEVEL
## https://android-review.googlesource.com/c/device/linaro/hikey/+/833021
cherrypick device/linaro/hikey 7271d39376570033a45b77eb1593be51d36db36b

## netd.te & net.te workaround for icmp_socket support
## http://android-review.linaro.org/#/c/device/linaro/hikey/+/19889
apply --linaro device/linaro/hikey 19889/2

## hikey: Totally remove FIQ console
## http://android-review.linaro.org/#/c/device/linaro/hikey/+/19971
apply --linaro device/linaro/hikey 19971/1

## enable basic system services features
## https://android-review.googlesource.com/c/device/linaro/hikey/+/857903
apply device/linaro/hikey 857903/2

## HiKey/HiKey960: Rework HiKey PowerHAL to use power@1.1 interface
## http://android-review.linaro.org/#/c/device/linaro/hikey/+/20049
apply --linaro device/linaro/hikey 20049/1

## enable drm hal feature
## https://android-review.googlesource.com/c/device/linaro/hikey/+/860444
apply device/linaro/hikey 860444/4

## mediacodec.te: allow dir read of system_file
## https://android-review.googlesource.com/c/device/linaro/hikey/+/860443
apply device/linaro/hikey 860443/1

## fstab.hikey: mount data with nosuid and nodev
## https://android-review.linaro.org/#/c/device/linaro/hikey/+/20067/
apply --linaro device/linaro/hikey 20067/1

## hikey: gralloc: Add element to allow upstream drm_hwc to build w/ HiKey
## https://android-review.googlesource.com/c/device/linaro/hikey/+/915654
cherrypick device/linaro/hikey 91d8213c9233c8c37bd8a0e2259d4aebd4618512
