#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
##  workaround for linaro work                   ######
#######################################################
## integrated tests
## http://android-review.linaro.org/17155
apply --linaro device/linaro/hikey 17155/4

## enabling kernel compilation, etc
## https://android-review.linaro.org/#/c/16834/
apply --linaro device/linaro/hikey 16834/10

## hikey_defconfig: Update defconfig to support upstream serialdev bt
## Switch over to using the serdev bluetooth implementation.
## revert for bt working with O-PDK
revert kernel/linaro/hisilicon 3e08cd937ab1a22f144a870b95a32dfe6fe44d17

## grub.cfg: set serialno for boot_fat.uefi.img
cherrypick device/linaro/hikey 1b85c5d479562abd2e55c5b2e73f75aecdda25d2

## init.common.rc: enable randomize_va_space
## https://android-review.linaro.org/#/c/17933/
apply --linaro device/linaro/hikey 17933/1

## hikey/BoardConfig.mk: add support for feature of android.software.cts
## http://android-review.linaro.org/17974
apply --linaro device/linaro/hikey 17974/2
