#!/bin/sh

. $(dirname $0)/functions

curl_am_optee(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local user=$4
    local patch_url="https://github.com/${user}/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
###### OP-TEE support on device config        ####
##################################################
## Integrate OP-TEE components
## optee: integrate for optee components
if [ X"$MANIFEST_BRANCH" = X"master" ]; then
	## http://android-review.linaro.org/17988
	apply --linaro device/linaro/hikey 17988/21
else
	## assume pie
	## http://android-review.linaro.org/20090
	apply --linaro device/linaro/hikey 20090/34
fi

if [ X"$TARGET_OUT_DIR" = X"hikey960" ] && { [ X"$LOCAL_MANIFEST_BRANCH" = X"linaro-p-swg" ] || [ X"$LOCAL_MANIFEST_BRANCH" = X"linaro-master-swg" ]; }; then
	## revert "Delete outdated uefi-build.sh"
	revert optee/uefi-tools 0407bb1a30ece4a305486535df5d4835c8241882

	## optee: Enable opteed in the bootloader (uefi-tools master)
	curl_am_optee uefi-tools ce5510f096c7b1fd6a428dcb85c81744288f9a1b optee/uefi-tools vchong
fi

###############################################
####      For debug purpose patches    ########
###############################################
## git commit subject
## http://android-review.linaro.org/12345
#apply --linaro device/linaro/hikey 12345/1
