#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack   ###################
##################################################
## Linaro patch for development based on the AOSP master branch

## integrated tests
## http://android-review.linaro.org/17155
apply --linaro device/linaro/hikey 17155/4

## enabling kernel compilation, etc
## https://android-review.linaro.org/#/c/16834/
apply --linaro device/linaro/hikey 16834/9

## revert "Switch Bluetooth HAL policy to _client/_server"
revert device/linaro/hikey 66b7b5ed3831dc07315b212d91c867c4cabbe8ad

## hikey: Add Bluetooth HAL sepolicy
revert device/linaro/hikey f66707691e05fa532a229d9b0f2d71be614be04a

## revert to have default serialno
revert device/linaro/hikey 128d7e6340d693af53bdecac28fd97d3ae8695ee

## revert changes for using internal fat16copy
revert device/linaro/hikey fcfe2d6ac00539f2d4cf77295503c0d285ee8170

## revert "hikey: Fix hci_attach sepolicy"
revert device/linaro/hikey a7097bfa8eb6fa4d6065af9923134b34629be0c2

## revert "Move hci_attach to hikey specific policy"
revert device/linaro/hikey bafa947af807e2908e18b5ab8d68e2c2456032eb
