#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
## Add support for hikey960_auto and hikey_auto products
## http://android-review.linaro.org/c/device/linaro/hikey/+/20614
## https://android-review.googlesource.com/c/device/linaro/hikey/+/1095112
apply device/linaro/hikey 1095112/2
