#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack   ###################
##################################################
## Enable TV support for Hikey
## http://android-review.linaro.org/17422
apply --linaro device/linaro/hikey 17422/1

##################################################
################ Linaro hack   ###################
##################################################
## Enable OPTEE support for AOSP TV on Hikey
## http://android-review.linaro.org/17488
## http://android-review.linaro.org/17489
## http://android-review.linaro.org/17490
## http://android-review.linaro.org/17491
apply --linaro device/linaro/hikey 17488/1
apply --linaro device/linaro/hikey 17489/1
apply --linaro device/linaro/hikey 17490/1
apply --linaro device/linaro/hikey 17491/1
