#!/bin/bash

### HiKey960 OPTEE "patch" for pull-requests coming from Github
###
### This patches the local manifest to adhere to what the SWG
### recommends as the starting point for OPTEE on HiKey960, but
### changes the Git revision of either OPTEE OS or Client to
### instead use a pull-request from Github, whichever
### triggered this build job.

#if [ "${ghprbPullId}" ]; then
    #echo "Applying Github pull-request #${ghprbPullId} from ${ghprbGhRepository}"

    lm=.repo/local_manifests
    if [ -d ${lm} ]; then
        echo "Get SWG's local manifest for OPTEE HiKey960 AOSP P"
        wget -O ${lm}/swg.xml \
            https://raw.githubusercontent.com/linaro-swg/optee_android_manifest/lcr-ref-hikey/swg-p-hikey960.xml

        # Patch SWG's local manifest with pull-request
        # Disable this for now since we've moved to daily/weekly builds
        #project=${ghprbGhRepository#OP-TEE/*}
        #sed -i -e "s|name=\"OP-TEE/${project}\".*revision=\"master\"|name=\"OP-TEE/${project}\" revision=\"refs/pull/${ghprbPullId}/head\"|" ${lm}/swg.xml

        # "Patch" OP-TEE to SWG + pull-request
        echo "Resync optee related repos to master"
        repo sync OP-TEE/optee_os OP-TEE/optee_client OP-TEE/optee_test device/l
inaro/kmgk

        echo "Sync bootloader repos"
        repo sync optee/arm-trusted-firmware optee/edk2 optee/OpenPlatformPkg optee/l-loader optee/tools-images-hikey960 optee/uefi-toolsk

        echo "Regenerate manifest"
        repo manifest -r -o pinned-manifest.xml
    else
        exit 1
    fi
#else
    #echo "WARNING: No Github pull-request was identified."
#fi
