#!/bin/bash -e

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
##  workaround for linaro work                   ######
#######################################################
## hikey960: workaround to compiling kernel for hikey960
## http://android-review.linaro.org/c/device/linaro/hikey/+/20388
apply --linaro device/linaro/hikey 20388/2

## hikey960: Add version check on the hisi vdec package
cherrypick device/linaro/hikey 221be176e245ec9deb22d6cba799777b4e9c8e3e
## hikey960: gralloc960: Add usage field to map to older code
cherrypick device/linaro/hikey 6b14a3306bb3c760c63fe48467f4e57b06616d82
## hikey960: gralloc960: Add support for building w/  drm_hwcomposer
cherrypick device/linaro/hikey b644c34ee96bbd432d653402a802b9743492877e
## hikey960: gralloc960: Tweak allocation so every HWC allocation doesn't come out of cma
cherrypick device/linaro/hikey a88fbc333e9d7c9723edba45a19dd643d87d1c36

## hikey960: Fix image sizes to match ptable
cherrypick device/linaro/hikey 1786ee2ac091fea9ab9424a721772ec46afd3def
## HiKey960: Add sys.usb.controller override for newer kernels
cherrypick device/linaro/hikey 0c244e86dcced923c1ac4e9fe137e1ae55064b48

## HiKey960: Set driver_match_existing_only to 0 to enable gadget mode to work on usb-c hotplug
## http://android-review.linaro.org/#/c/device/linaro/hikey/+/20209 HiKey960
apply --linaro device/linaro/hikey 20209/1

## HACK: drm: kirin960: Add DSI mode 800x480@66
## http://android-review.linaro.org/#/c/kernel/hikey-linaro/+/20204
apply --linaro --local kernel/linaro/hisilicon-4.14 --remote kernel/hikey-linaro 20204/1
