#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack   ###################
##################################################
## Linaro patch for development based on the AOSP master branch
## revert hack for dhcpcd_eth0 service
revert device/linaro/hikey 4c1238443cce2a0c0a689ab60d09f2df2a0500c7

## revert removal of  definition of configfs
revert device/linaro/hikey 644d7abe37111bbd9b83486bc449e96a49c8cf30

## rules for marshmallow
## http://android-review.linaro.org/17114
apply --linaro device/linaro/hikey 17114/1

## backport AOSP master change for netlink socket classes
## for SELinux support
##http://android-review.linaro.org/16931
apply --linaro external/sepolicy 16931/1

## hack workaround for tracefs
## http://android-review.linaro.org/16932
apply --linaro external/sepolicy 16932/1
