#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
##  workaround for linaro work                   ######
#######################################################
## integrated tests
## http://android-review.linaro.org/17155
apply --linaro device/linaro/hikey 17155/8

## enabling kernel compilation, etc
## enable kernel compilation for hikey build
## http://android-review.linaro.org/18395
apply --linaro device/linaro/hikey 18395/1
