#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
##  workaround for linaro work                   ######
#######################################################
cd device/linaro/hikey
git pull https://android.googlesource.com/device/linaro/hikey refs/changes/73/803573/1
cd -

## domain.te: Add map permissions to vendor_config_files
## http://android-review.linaro.org/#/c/device/linaro/hikey/+/19582
apply --linaro device/linaro/hikey 19582/1

## sepolicy/vendor_init.te: Allow mmap for vendor_init
## http://android-review.linaro.org/#/c/device/linaro/hikey/+/19596
apply --linaro device/linaro/hikey 19596/1

## http://android-review.linaro.org/#/c/device/linaro/hikey/+/19677
## sepolicy/system_server.te: Explicitly allow system_server to (m)map data files
apply --linaro device/linaro/hikey 19677/1

## Relax some neverallow rules
## bd3e300a1309323e02c7144202acb48f40f11946
#cherrypick system/sepolicy bd3e300a1309323e02c7144202acb48f40f11946

## https://android-review.linaro.org/#/c/platform/system/sepolicy/+/19867/
## system/sepolicy/*/domain.te
## Add support for RS vendor executables.
apply --linaro system/sepolicy 19867/1

## integrated tests
## http://android-review.linaro.org/17155
apply --linaro device/linaro/hikey 17155/8

## enabling kernel compilation, etc
## enable kernel compilation for hikey build
## http://android-review.linaro.org/19846
apply --linaro device/linaro/hikey 19846/1

## drm/hisilicon: Ensure LDI regs are properly configured.
## commit a2f042430784d86eb2b7a6d2a869f552da30edba upstream.
revert kernel/linaro/hisilicon-4.14 f5e69000aa80880491ca4a613679bd21c60b048b 

# mm: hide incomplete nr_indirectly_reclaimable in /proc/zoneinfo
# https://lore.kernel.org/patchwork/patch/1004601/mbox/
pushd kernel/linaro/hisilicon-4.14
curl https://lore.kernel.org/patchwork/patch/1004601/mbox/ |git am
popd

## hikey960: Add version check on the hisi vdec package
cherrypick device/linaro/hikey 221be176e245ec9deb22d6cba799777b4e9c8e3e
## hikey960: gralloc960: Add usage field to map to older code
cherrypick device/linaro/hikey 6b14a3306bb3c760c63fe48467f4e57b06616d82
## hikey960: gralloc960: Add support for building w/  drm_hwcomposer
cherrypick device/linaro/hikey b644c34ee96bbd432d653402a802b9743492877e
## hikey960: gralloc960: Tweak allocation so every HWC allocation doesn't come out of cma
cherrypick device/linaro/hikey a88fbc333e9d7c9723edba45a19dd643d87d1c36

## hikey960: Enable verity for hikey960
cherrypick device/linaro/hikey a2106d17f7423fbcee88063e478945269f59ad67
## hikey{,960}: Enable system-as-root and verity.
cherrypick device/linaro/hikey 11c5e3e98827c301fc6a5364ae8b7dab93a22de4

## hikey960: Fix image sizes to match ptable
cherrypick device/linaro/hikey 1786ee2ac091fea9ab9424a721772ec46afd3def
## HiKey960: Add sys.usb.controller override for newer kernels
cherrypick device/linaro/hikey 0c244e86dcced923c1ac4e9fe137e1ae55064b48

## For using drm_hwcomposer introduced by kernel change here:
## https://android-review.googlesource.com/c/kernel/hikey-linaro/+/743922
## hikey/hikey960: Enable drm_hwcomposer for 4.14+ kernels
## https://android-review.googlesource.com/c/device/linaro/hikey/+/737121
cherrypick device/linaro/hikey 6dc5ce5dbcd79e6fb6abb157e24b381d4f09d04a
## hikey: Enable drm_hwcomposer on 4.9 kernels
## https://android-review.googlesource.com/c/device/linaro/hikey/+/748113
cherrypick device/linaro/hikey 890bbe447ca065bd9d325d1fc14ceebd040b50a4
## hikey: gralloc: Change to allow gralloc_priv.h to be shared
cherrypick device/linaro/hikey 25d6129aed2ffa8a7d502c3703f82500ecc3a2ad
## hikey: gralloc: Add union alias and additional fields to improve interop w/ hikey960 gralloc
cherrypick device/linaro/hikey 30941517aac192a55dc358479e27dc6a6b3bc04e
## hikey: gralloc: Allow use of CMA heap instead of fbdev
cherrypick device/linaro/hikey f3d868dcbd74d43b754bf168fd5f63bf4c8c4385

## hikey960: bifrost: Update mali bifrost blobs to r10p0
cherrypick device/linaro/hikey 6cd25833e0d164313ffd94958905940f4a196963
## hikey960: bifrost: Add renderscript binary dependencies
cherrypick device/linaro/hikey be064a22950781778b0079d6a2db06c0fc4180de
## hikey960: bifrost: Enable renderscript binaries
cherrypick device/linaro/hikey a6764b2e0dcd63745b6abd12928bdab15d48494c

## hikey/hikey960: Fix powerHAL not loading
cherrypick device/linaro/hikey a0e71f625bfe652fe47791d512487f854d7cf175

## revert change of "Make libdrm recovery_available" from master branch
revert external/libdrm d9aac04d6cd8fb78ad600fe4d252b94877ba39bf

## device-common.mk: set PRODUCT_SHIPPING_API_LEVEL
## https://android-review.googlesource.com/c/device/linaro/hikey/+/833021
apply device/linaro/hikey 833021/1

## public/netd.te: allow netd to operate icmp_socket that passed to it
## http://android-review.linaro.org/#/c/device/linaro/hikey/+/19889
apply --linaro device/linaro/hikey 19889/1
