#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
###### OP-TEE support on device config        ####
##################################################
## Integrate OP-TEE components
## http://android-review.linaro.org/16991
apply --linaro device/linaro/hikey 16991/9

## OP-TEE SELinux
## https://android-review.linaro.org/#/c/17177/
apply --linaro device/linaro/hikey 17177/6

## Enable OP-TEE in the bootloader
## https://android-review.linaro.org/#/c/17488/
apply --linaro device/linaro/hikey 17488/3
