#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack   ###################
##################################################
## Linaro patch for development based on the AOSP master branch
## revert hack for dhcpcd_eth0 service
revert device/linaro/hikey 4c1238443cce2a0c0a689ab60d09f2df2a0500c7

## patches for kernel compilation based on the AOSP master branch
## https://android-review.linaro.org/#/c/16834/
apply --linaro device/linaro/hikey 16834/3
