#!/bin/sh

. $(dirname $0)/functions

curl_am_hikey_optee(){
    local patch_id=$1
    local patch_url="https://git.linaro.org/kernel/linux-linaro-stable.git/patch/?id=${patch_id}"
    local patch_project="kernel/linaro/hisilicon"
    curl_am ${patch_url} ${patch_project}
}

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
###### OP-TEE support on device config        ####
##################################################
## Integrate OP-TEE components
## optee: integrate for optee components
## http://android-review.linaro.org/17988
apply --linaro device/linaro/hikey 17988/5
## OP-TEE selinux
## https://android-review.linaro.org/#/c/17177/
apply --linaro device/linaro/hikey 17177/13
## init.common.rc & sepolicy: move OPTEE related file to vendor paritition
## http://android-review.linaro.org/18404
apply --linaro device/linaro/hikey 18404/3

## optee: Enable opteed in the bootloader
## http://android-review.linaro.org/18233
apply --linaro device/linaro/hikey 18233/2
## bootloader/Makefile: use TOP_ROOT_ABS instead of ANDROID_BUILD_TOP
## https://android-review.linaro.org/#/c/18470/
apply --linaro device/linaro/hikey 18470/1
## build_uefi.mk: to build uefi files automatically when build android
## https://android-review.linaro.org/#/c/17728/
apply --linaro device/linaro/hikey 17728/6
