#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack   ###################
##################################################
## delay in init for usb device to be detected  ##
apply --linaro system/core 18180/1

## sf: Initialize DispSync in SurfaceFlinger_hwc1
## which fixed the problem of "W SurfaceFlinger: Timed out waiting for hw vsync; faking it"
## for devices when swithce to use with 8.1.0_r1
## https://android-review.googlesource.com/c/platform/frameworks/native/+/519520
cherrypick frameworks/native c9d2db18d8154ef527dbf4d34c7bb3317bbdc98c

