#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_amit_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/amit.pundir/linux.git/patch/?id=${commit_id} ${target_dir}
    fi
}

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} ${target_dir}
    fi
}

function apply_patchwork(){
    local patch_id=$1 && shift
    local target_dir="common"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://lore.kernel.org/patchwork/patch/${patch_id}/mbox/ ${target_dir}
    fi
}
##################################################
################ Linaro hack   ###################
##################################################
######### temporary workarounds for sdcardfs ##################
## ANDROID: vfs: Add setattr2 for filesystems with per mount permissions
revert common 584c54745dab64b304485ea16e0dff1811e5598a
## ANDROID: vfs: Add permission2 for filesystems with per mount permissions
revert common c3271fe2811ccd13106ac370cf4cef79bb49117e
## ANDROID: vfs: add d_canonical_path for stacked filesystem support
revert common 972cde43ff770d43987655d37bc49156c7c6f889
## ANDROID: fs: Restore vfs_path_lookup() export
revert common e9aaf35681c274c98a3dda427b086a9782f96d33
## ANDROID: sdcardfs: remove sdcardfs from system
revert common a96c98dd7a3087f0c415bb05699f25722f8aef11
