#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_amit_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/amit.pundir/linux.git/patch/?id=${commit_id} ${target_dir}
    fi
}

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} ${target_dir}
    fi
}
##################################################
################ Linaro hack   ###################
##################################################
## gki_defconfig & db845c_gki.fragment: initial commit
## http://android-review.linaro.org/c/kernel/common/+/21034
apply --linaro --local kernel/common/mainline --remote kernel/common 21034/5

## arm64: dts/sdm845: Enable FW implemented safe sequence handler on MTP
## https://git.linaro.org/people/amit.pundir/linux.git/commit/arch/arm64/boot/dts/qcom/sdm845.dtsi?h=dragonboard-android-mainline-tracking&id=e6da023586fb35290b2fedfb14fc9ea0a13365d7
## http://android-review.linaro.org/c/kernel/common/+/21026
apply --linaro --local kernel/common/mainline --remote kernel/common 21026/1
## arm64: dts: qcom: sdm845: Add first PCIe controller and PHY
## https://git.linaro.org/people/amit.pundir/linux.git/commit/arch/arm64/boot/dts/qcom/sdm845.dtsi?h=dragonboard-android-mainline-tracking&id=bcf7783b1bc95a39f66f287f4a5d6720f08df421
## http://android-review.linaro.org/c/kernel/common/+/21027
apply --linaro --local kernel/common/mainline --remote kernel/common 21027/1
## arm64: dts: qcom: sdm845: Add second PCIe PHY and controller
## https://git.linaro.org/people/amit.pundir/linux.git/commit/arch/arm64/boot/dts/qcom/sdm845.dtsi?h=dragonboard-android-mainline-tracking&id=ae2dd32777ec214ff53dbba726de42f9e0385e1e
## http://android-review.linaro.org/c/kernel/common/+/21025
apply --linaro --local kernel/common/mainline --remote kernel/common 21025/2

## arm64: dts: qcom: db845c: Enable PCIe controllers
## https://git.linaro.org/people/amit.pundir/linux.git/commit/arch/arm64/boot/dts/qcom/sdm845-db845c.dts?h=dragonboard-android-mainline-tracking&id=8857c881f9fe2087d59f67261dc1d844f7888093
apply_amit_mainline_patch 8857c881f9fe2087d59f67261dc1d844f7888093
## arm64: dts: qcom: sdm845-db845c: Bring in LT9611
## https://git.linaro.org/people/amit.pundir/linux.git/commit/arch/arm64/boot/dts/qcom/sdm845-db845c.dts?h=dragonboard-android-mainline-tracking&id=44599f11ca9709771c224277fa2eefdbcbcc2b45
apply_amit_mainline_patch 44599f11ca9709771c224277fa2eefdbcbcc2b45
## arm64: dts: db845c: add Low speed expansion i2c and spi nodes
## https://git.linaro.org/people/amit.pundir/linux.git/commit/arch/arm64/boot/dts/qcom/sdm845-db845c.dts?h=dragonboard-android-mainline-tracking&id=f9f9dd1eb74be5c176471d67865f946d2a6862b7
apply_amit_mainline_patch f9f9dd1eb74be5c176471d67865f946d2a6862b7

## HACK: drm: msm: quiet down plane errors
## https://git.linaro.org/people/amit.pundir/linux.git/commit/drivers/gpu/drm/msm?h=dragonboard-android-mainline-tracking&id=589cb23b09e01d2395bccd3bf328fcce87ad29c4
apply_amit_mainline_patch 589cb23b09e01d2395bccd3bf328fcce87ad29c4

## drm/bridge: Introduce LT9611 DSI to HDMI bridge
## https://git.linaro.org/people/amit.pundir/linux.git/commit/drivers/gpu/drm/bridge?h=dragonboard-android-mainline-tracking&id=2e689901395bee6ab3e3c9cd4c19477b412cab7a
## http://android-review.linaro.org/c/kernel/common/+/21082
apply --linaro --local kernel/common/mainline --remote kernel/common 21082/1
## drm/bridge: lt9611: Add i2s initialization
## https://git.linaro.org/people/amit.pundir/linux.git/commit/drivers/gpu/drm/bridge?h=dragonboard-android-mainline-tracking&id=296790cbfb674391d487261cf037dc67efd474d1
apply_amit_mainline_patch 296790cbfb674391d487261cf037dc67efd474d1
## HACK: db845c: drm/bridge: lt9611: comment out lt9611_sleep_setup()
## https://git.linaro.org/people/amit.pundir/linux.git/commit/drivers/gpu/drm/bridge?h=dragonboard-android-mainline-tracking&id=721acad5f2b8b0d7693d7b543567fd60919cc65b
apply_amit_mainline_patch 721acad5f2b8b0d7693d7b543567fd60919cc65b
## drivers/gpu/drm/bridge/lt9611.c: fix for the drop of drm/drmP.h
## http://android-review.linaro.org/c/kernel/common/+/21083
apply --linaro --local kernel/common/mainline --remote kernel/common 21083/1

## usb: xhci: add firmware loader for uPD720201 and uPD720202 w/o ROM
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=d76d7882108b7690ea24d7e805e431c6a23f377b
apply_jstultz_mainline_patch d76d7882108b7690ea24d7e805e431c6a23f377b
## usb: xhci: handle uPD720201 and uPD720202 w/o ROM
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=bf7a37a8cef1c48ca837ad10829eff70a0d645dc
apply_jstultz_mainline_patch bf7a37a8cef1c48ca837ad10829eff70a0d645dc
## usb: xhci: Use register defined and field names
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=934c3b0fd3c09b8d26b28210149e0cdf85d26b81
apply_jstultz_mainline_patch 934c3b0fd3c09b8d26b28210149e0cdf85d26b81
## usb: xhci: Add ROM loader for uPD720201
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=bc17ada1518c545025a72b49941d41518ff3ca3c
apply_jstultz_mainline_patch bc17ada1518c545025a72b49941d41518ff3ca3c
## usb: xhci: allow multiple firmware versions
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=834d686f33475781da3257c173065f47e9b00b44
apply_jstultz_mainline_patch 834d686f33475781da3257c173065f47e9b00b44
## usb: xhci: provide a debugfs hook for erasing rom
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=a6828bf973da17e6a35ac47e735a748b85eee62c
apply_jstultz_mainline_patch a6828bf973da17e6a35ac47e735a748b85eee62c

## db845c: Add build config
## https://git.linaro.org/people/amit.pundir/linux.git/commit/build.config.db845c?h=dragonboard-android-mainline-tracking&id=5b2307b358573cd2834f947438b42e3d0468c979
apply_amit_mainline_patch 5b2307b358573cd2834f947438b42e3d0468c979
## db845c: Update build config
## https://git.linaro.org/people/amit.pundir/linux.git/commit/build.config.db845c?h=dragonboard-android-mainline-tracking&id=b35c74fca800d82486b94583714767d1e5e764af
apply_amit_mainline_patch b35c74fca800d82486b94583714767d1e5e764af

## HACK: usb: dwc3: Disable sg_supported in order to avoid USB transfer errors
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/dwc3?h=dev/db845c-v5.4-gki&id=409ccd61f19a8b90c74d2c6d4a81fc33921080d2
apply_jstultz_mainline_patch 409ccd61f19a8b90c74d2c6d4a81fc33921080d2
