#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local local_dir=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} ${local_dir}
}

##################################################
################ Linaro hack   ###################
##################################################
## drm/exynos: dsi: Fix bridge chain handling
revert common f66ff55a9bd06855f9c6b8f29d8760f77bfe43c2
## drm/vc4: dsi: Fix bridge chain handling
revert common 033bfe7538a1523f36dd434eaff7c754a555c458
## drm/bridge: Clarify the atomic enable/disable hooks semantics
revert common f3fdbc721b8bc99c692716cf9a3cf061b5a49a18
## drm/bridge: Make the bridge chain a double-linked list
revert common 05193dc38197021894b17239fafbd2eb1afe5a45
## drm/bridge: Add the drm_bridge_get_prev_bridge() helper
revert common ac877c64c87aff5d228cf53e40d8f68899afa815
##  drm/bridge: Add the drm_for_each_bridge_in_chain() helper
revert common 4ec5c9050a496a984ffdaaf2307aef353634dc87
