#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local local_dir=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} ${local_dir}
}

##################################################
################ Linaro hack   ###################
##################################################
## gki: add hikey960_gki.fragment and udpate gki_defconfig for hikey960 [NEW]
## http://android-review.linaro.org/c/kernel/common/+/20887
apply --linaro --local common --remote kernel/common 20887/3
apply --linaro --local kernel/common/mainline --remote kernel/common 20887/3

## Workaround to display homescreen on hdmi monitor
## Revert "ANDROID: staging: ion: add support for consistent heap ids"
## http://android-review.linaro.org/c/kernel/common/+/20882
## https://android-review.googlesource.com/c/kernel/common/+/1108639
apply --linaro --local common --remote kernel/common 20882/1
