#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} common
}

##################################################
################ Linaro hack   ###################
##################################################
## https://android-review.linaro.org/c/kernel/common/+/20784/
apply --linaro --local common --remote kernel/common 20784/6
apply --linaro --local kernel/common/mainline --remote kernel/common 20784/6

## gki: Kconfig: regmap: Add REGMAP_DUMMY_MODULE option
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=d02c6fa9357c5ef1a0f38d7c48261b6b6511a037
apply_jstultz_mainline_patch d02c6fa9357c5ef1a0f38d7c48261b6b6511a037
