#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} kernel/common/mainline
}

##################################################
################ Linaro hack   ###################
##################################################
## HACK: dts: hi6220: Add special mali utgard driver dts properties
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/arch/arm64/boot/dts?h=dev/hikey-mainline-WIP&id=c6f4b61a0d9622b706019625b35d4f51a35d2992
## https://android-review.linaro.org/c/kernel/common/+/21855
apply --linaro --local kernel/common/mainline --remote kernel/common 21855/1

## adv7511: Disable HPD sensing before powering on the chip
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey-mainline-WIP&id=1dfbbfe35b44a1b566e92122bae0c65452f47ad7
## https://android-review.linaro.org/c/kernel/common/+/21856
apply --linaro --local kernel/common/mainline --remote kernel/common 21856/3
## HACK: adv7511: Add poweron delay to allow for EDID probing to work
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey-mainline-WIP&id=3d75a489eec692e54abcd5048946d7169d9af120
## https://android-review.linaro.org/c/kernel/common/+/21857
apply --linaro --local kernel/common/mainline --remote kernel/common 21857/2
## temp hack to make display work
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey-mainline-WIP&id=f3513568f11b21088ff8da2bba7a4025bb44c18b
## https://android-review.linaro.org/c/kernel/common/+/21858
apply --linaro --local kernel/common/mainline --remote kernel/common 21858/2

## ANDROID: dma: Rework so dev_get_cma_area() can be called from a module
## https://android-review.googlesource.com/c/kernel/common/+/1422535
apply --local kernel/common/mainline --remote kernel/common 1422535/10
## ANDROID: dma-buf: heaps: Allow cma heaps to be configured as a module
## https://android-review.googlesource.com/c/kernel/common/+/1422536
apply --local kernel/common/mainline --remote kernel/common 1422536/10
