#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_amit_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/amit.pundir/linux.git/patch/?id=${commit_id} ${target_dir}
    fi
}

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} ${target_dir}
    fi
}

function apply_patchwork(){
    local patch_id=$1 && shift
    local target_dir="common"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://lore.kernel.org/patchwork/patch/${patch_id}/mbox/ ${target_dir}
    fi
}
##################################################
################ Linaro hack   ###################
##################################################
######### temporary workarounds for sdcardfs ##################
## ANDROID: vfs: Add setattr2 for filesystems with per mount permissions
apply --linaro --local common --remote kernel/common 21553/4
## ANDROID: vfs: Add permission2 for filesystems with per mount permissions
apply --linaro --local common --remote kernel/common 21554/6
## ANDROID: vfs: add d_canonical_path for stacked filesystem support
## https://android-review.linaro.org/c/kernel/common/+/21555
apply --linaro --local common --remote kernel/common 21555/4
## ANDROID: fs: Restore vfs_path_lookup() export
## https://android-review.linaro.org/c/kernel/common/+/21556
apply --linaro --local common --remote kernel/common 21556/3
## ANDROID: sdcardfs: remove sdcardfs from system
apply --linaro --local common --remote kernel/common 21557/3
## ANDROID: fscrypt: add key removal notifier chain
apply --linaro --local common --remote kernel/common 21612/2
## Revert "Revert "ANDROID: mnt: Add filesystem private data to mount points""
## http://android-review.linaro.org/c/kernel/common/+/21705
apply --linaro --local common --remote kernel/common 21705/1
## Revert "Revert "ANDROID: mnt: Fix null pointer dereference""
## http://android-review.linaro.org/c/kernel/common/+/21706
apply --linaro --local common --remote kernel/common 21706/1
## Revert "Revert "ANDROID: Add show_options2 to view private mount data""
## http://android-review.linaro.org/c/kernel/common/+/21707
apply --linaro --local common --remote kernel/common 21707/1
