#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi
##################################################
################ Linaro hack   ###################
##################################################
## db845c: Add support for cache partition
## https://android.googlesource.com/device/linaro/dragonboard/+/70f37c65199443d2502da58ecb81a4be28d36d80%5E%21/
#cherrypick device/linaro/dragonboard 70f37c65199443d2502da58ecb81a4be28d36d80

## db845c.mk: set DB845C_KERNEL_DIR to use environment when specified
## https://android-review.googlesource.com/c/device/linaro/dragonboard/+/1462043
apply device/linaro/dragonboard 1462043/1
