#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi
##################################################
################ Linaro hack   ###################
##################################################
## hikey/hikey960: init.common.usb.rc: Add setprop sys.usb.controller to avoid picking the dummy hcd
## https://android-review.googlesource.com/c/device/linaro/hikey/+/1425648
apply --local device/linaro/hikey --remote device/linaro/hikey 1425648/1
