#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local local_dir=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} ${local_dir}
}

##################################################
################ Linaro hack   ###################
##################################################
## https://android-review.linaro.org/c/kernel/common/+/20784/
apply --linaro --local kernel/common/mainline --remote kernel/common 20784/18

## revert ANDROID: serdev: add platform device support
revert common 9b460a068c2b441d8a8dfb04740004b8b747f10f
revert common c550a54f23026e92633c5145e8b919cf590a5624

## revert usb: dwc3: gadget: Fix logical condition
revert common 8c7d4b7b3d43c54c0b8c1e4adb917a151c754196
