#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_amit_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="common"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/amit.pundir/linux.git/patch/?id=${commit_id} ${target_dir}
    fi
}

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="common"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} ${target_dir}
    fi
}
##################################################
################ Linaro hack   ###################
##################################################
## gki_defconfig & db845c_gki.fragment: initial commit
## http://android-review.linaro.org/c/kernel/common/+/21034
apply --linaro --local common --remote kernel/common 21034/5

## ANDORID: iommu: arm-smmu: Don't blindly use first SMR to calculate mask
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/iommu/arm-smmu.c?h=dev/db845c-v5.4-gki&id=0c3385706d1b6714aafbe4590730001e0917977e
## http://android-review.linaro.org/c/kernel/common/+/21028
apply --linaro --local common --remote kernel/common 21028/1
## ANDROID: iommu: arm-smmu: Handoff SMR registers and context banks
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/iommu/arm-smmu.c?h=dev/db845c-v5.4-gki&id=df98d3dfce3c26896361c2aad7a88ba46c7e36a6
## http://android-review.linaro.org/c/kernel/common/+/21029
apply --linaro --local common --remote kernel/common 21029/1

## HACK: usb: dwc3: Disable sg_supported in order to avoid USB transfer errors
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/dwc3?h=dev/db845c-v5.4-gki&id=409ccd61f19a8b90c74d2c6d4a81fc33921080d2
apply_jstultz_mainline_patch 409ccd61f19a8b90c74d2c6d4a81fc33921080d2
