#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} kernel/common/mainline
}

##################################################
################ Linaro hack   ###################
##################################################
##############FOR ADB STUCK####################
## usb: gadget: f_fs: Allow scatter-gather buffers
## caused by commit 772a7a724f69d258025fedd87dde1aafe4171aef
## usb: dwc3: Check for IOC/LST bit in both event->status and TRB->ctrl fields
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=2a8dc8cf7b0b209c0d96ed27d79964b97dcf64c2
apply_jstultz_mainline_patch 2a8dc8cf7b0b209c0d96ed27d79964b97dcf64c2
