#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} kernel/common/mainline
}

##################################################
################ Linaro hack   ###################
##################################################
## HACK: dts: hi6220: Add special mali utgard driver dts properties
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey-mainline-WIP&id=1b6f902017613cf6e0345601a8fc4b7f1ce189a4
apply_jstultz_mainline_patch 1b6f902017613cf6e0345601a8fc4b7f1ce189a4

## adv7511: Disable HPD sensing before powering on the chip
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey-mainline-WIP&id=8682bbeada3eca42e6eaa90a6a6c0feacceaa5d4
apply_jstultz_mainline_patch 8682bbeada3eca42e6eaa90a6a6c0feacceaa5d4
## HACK: adv7511: Add poweron delay to allow for EDID probing to work
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey-mainline-WIP&id=16d03eb253314ae1b6a43951f78bb7aeeb6ba77b
apply_jstultz_mainline_patch 16d03eb253314ae1b6a43951f78bb7aeeb6ba77b
## temp hack to make display work
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey-mainline-WIP&id=fbc923819d0f41b5a4cdcaf15dd32ff83aaf7865
apply_jstultz_mainline_patch fbc923819d0f41b5a4cdcaf15dd32ff83aaf7865
