#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} kernel/common/mainline
}

##################################################
################ Linaro hack   ###################
##################################################
## add hikey_gki.fragment for gki build
## https://android-review.linaro.org/c/kernel/common/+/20784/
apply --linaro --local kernel/common/mainline --remote kernel/common 20784/21

## revert clk: hi6220: use CLK_OF_DECLARE_DRIVER
revert kernel/common/mainline f1edb498bd9f25936ae3540a8dbd86e6019fdb95
revert common f1edb498bd9f25936ae3540a8dbd86e6019fdb95

## revert drm: kirin: Revert "Fix for hikey620 display offset problem"
revert kernel/common/mainline 1b79cfd99ff5127e6a143767b51694a527b3ea38
## drm: kirin: Tweak the LDI handling
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=d378170e0055c8762df038c8b7e5c1561f44e0e8
apply_jstultz_mainline_patch d378170e0055c8762df038c8b7e5c1561f44e0e8
## another try at LDI fix
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=5d066b8fea8bd13ce382210638f8451816f2dfa0
apply_jstultz_mainline_patch 5d066b8fea8bd13ce382210638f8451816f2dfa0
