#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} kernel/common/mainline
}

##################################################
################ Linaro hack   ###################
##################################################
## drm: kirin: Fix for hikey620 display offset problem
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=bcc2b89a537ff187923a9c04931f823079667aa9
apply_jstultz_mainline_patch bcc2b89a537ff187923a9c04931f823079667aa9

## drm: kirin: Remove HISI_KIRIN_DW_DSI config option
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=86365439b15b5732224ed88bbb6c2261f5e2162d
apply_jstultz_mainline_patch 86365439b15b5732224ed88bbb6c2261f5e2162d

## drm: kirin: Remove unreachable return
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=df5ef849e4bd2c73562136e3a23e99c3dc623aeb
apply_jstultz_mainline_patch df5ef849e4bd2c73562136e3a23e99c3dc623aeb

## drm: kirin: Remove uncessary parameter indirection
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=36ee18d7b6b2d032f6b9b17659af864af60eae9c
apply_jstultz_mainline_patch 36ee18d7b6b2d032f6b9b17659af864af60eae9c

## drm: kirin: Remove out_format from ade_crtc
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=e212653856b6c39fd4bbf2584132183b553b2b7f
apply_jstultz_mainline_patch e212653856b6c39fd4bbf2584132183b553b2b7f

## drm: kirin: Rename ade_plane to kirin_plane
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=7da273525606d2d423d94ace627d2e0b730a0a8b
apply_jstultz_mainline_patch 7da273525606d2d423d94ace627d2e0b730a0a8b

## drm: kirin: Rename ade_crtc to kirin_crtc
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=504c737271c5cdf5893fbc73bf08839e148c431b
apply_jstultz_mainline_patch 504c737271c5cdf5893fbc73bf08839e148c431b

## drm: kirin: Dynamically allocate the hw_ctx
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=b5819f14be6f9fd48c27e132421bd4e2438dc4c0
apply_jstultz_mainline_patch b5819f14be6f9fd48c27e132421bd4e2438dc4c0

## drm: kirin: Move request irq handle in ade hw ctx alloc
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=df1640b9a2f25388527621877a49381cb2da0e9c
apply_jstultz_mainline_patch df1640b9a2f25388527621877a49381cb2da0e9c

## drm: kirin: Move workqueue to ade_hw_ctx structure
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=1197be082ad7e64f3f7cd6b0225e92a1e170eb48
apply_jstultz_mainline_patch 1197be082ad7e64f3f7cd6b0225e92a1e170eb48

## drm: kirin: Move kirin_crtc, kirin_plane, kirin_format to kirin_drm_drv.h
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=df90aeece3da4e43d8a6558a7c1c07cd4f54d524
apply_jstultz_mainline_patch df90aeece3da4e43d8a6558a7c1c07cd4f54d524

## drm: kirin: Reanme dc_ops to kirin_drm_data
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=38f6403d8cf543a3cead9ca3719355ca194b5b56
apply_jstultz_mainline_patch 38f6403d8cf543a3cead9ca3719355ca194b5b56

## drm: kirin: Move ade crtc/plane help functions to driver_data
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=b918ea9ae9e5bfc8f993d19319b9279a83ed50b4
apply_jstultz_mainline_patch b918ea9ae9e5bfc8f993d19319b9279a83ed50b4

## drm: kirin: Move channel formats to driver data
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=24793da063a16ef5bf409b459a1621ff8cd10444
apply_jstultz_mainline_patch 24793da063a16ef5bf409b459a1621ff8cd10444

## drm: kirin: Move mode config function to driver_data
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=c452114a92a977ac8386ccd7743cddb026609d11
apply_jstultz_mainline_patch c452114a92a977ac8386ccd7743cddb026609d11

## drm: kirin: Move plane number and primay plane in driver data
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=ad1325f0e6fdc4d208391d0535617102278c02d7
apply_jstultz_mainline_patch ad1325f0e6fdc4d208391d0535617102278c02d7

## drm: kirin: Move config max_width and max_height to driver data
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=f09d839a40035213aaaffaa7a0e67f8205f957ad
apply_jstultz_mainline_patch f09d839a40035213aaaffaa7a0e67f8205f957ad

## drm: kirin: Move drm driver to driver data
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=a9e0884f8ee279038637e621b5060e1fe1585244
apply_jstultz_mainline_patch a9e0884f8ee279038637e621b5060e1fe1585244

## drm: kirin: Add register connect helper functions in drm init
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=0e3614f1a0144fad2a0bb92a1cc672f80156173c
apply_jstultz_mainline_patch 0e3614f1a0144fad2a0bb92a1cc672f80156173c

## drm: kirin: Rename plane_init and crtc_init
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=83c8197edf642f83e00c5b2bee4634dc63fd02e4
apply_jstultz_mainline_patch 83c8197edf642f83e00c5b2bee4634dc63fd02e4

## drm: kirin: Fix dev->driver_data setting
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=38cd8c35c275997b71865b0307bf6945ebff5cf3
apply_jstultz_mainline_patch 38cd8c35c275997b71865b0307bf6945ebff5cf3

## drm: kirin: Make driver_data variable non-global
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=8df06eb113a0c5be1cb75363f59dfef7f017cbb4
apply_jstultz_mainline_patch 8df06eb113a0c5be1cb75363f59dfef7f017cbb4

## drm: kirin: Add alloc_hw_ctx/clean_hw_ctx ops in driver data
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=eadc8c14a24fb3a05e999b138effe0e979a0c720
apply_jstultz_mainline_patch eadc8c14a24fb3a05e999b138effe0e979a0c720

## drm: kirin: Pass driver data to crtc init and plane init
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=18e07e297ec838a3238bda2e00791e2ea0f114b1
apply_jstultz_mainline_patch 18e07e297ec838a3238bda2e00791e2ea0f114b1

## drm: kirin: Move ade drm init to kirin drm drv
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=a75e7f412a32a5de109faf883d0dec107d9aef50
apply_jstultz_mainline_patch a75e7f412a32a5de109faf883d0dec107d9aef50

## drm: kirin: Introduce kirin960
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=72b6263d3d62f4c6e1f78c1c4e6db30b88e59a95
apply_jstultz_mainline_patch 72b6263d3d62f4c6e1f78c1c4e6db30b88e59a95

## drm: kirin: Add kirin960 dpe driver support
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=b6fbc6ece0383dcf8eb6c4e93220367ec5b5e58f
apply_jstultz_mainline_patch b6fbc6ece0383dcf8eb6c4e93220367ec5b5e58f

## drm: kirin: Remove LDI enable
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=81c95099d681269cce77cc2d93c60828ea337445
apply_jstultz_mainline_patch 81c95099d681269cce77cc2d93c60828ea337445

## drm: kirin: remove wait for VACTIVE IRQ
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=d825488502761baa5c0749f1ab71257300c0243f
apply_jstultz_mainline_patch d825488502761baa5c0749f1ab71257300c0243f

## drm: kirin_drm_dpe: Fix rdma_stride calculation
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=a667a1e42c0b9595b0348bfd26980c7b82a1d2f1
apply_jstultz_mainline_patch a667a1e42c0b9595b0348bfd26980c7b82a1d2f1

## drm: kirin960: Remove one mode-line that seems to be causing trouble
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=088f12fe0da5f67583039377eb945a17b70a6ed5
apply_jstultz_mainline_patch 088f12fe0da5f67583039377eb945a17b70a6ed5

## hikey_defconfig: enable CONFIG_DRM_HISI_KIRIN620
## http://android-review.linaro.org/c/kernel/common/+/20518
apply --linaro --local kernel/common/mainline --remote kernel/common 20518/1
