#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} kernel/common/mainline
}

############### support for sdcardfs ====================================
## need for cts test, otherwise "Device must have external storage mounted in order to run CTS" will be reported
## ANDROID: sdcardfs: Enable modular sdcardfs
## http://android-review.linaro.org/c/kernel/common/+/20492
## cherrypick kernel/common/mainline 50f0dd432bf59a71ac8c246b14de2e17701b3ab9
## https://android-review.googlesource.com/c/kernel/common/+/983028
apply --local kernel/common/mainline --remote kernel/common 983028/1

## ANDROID: mnt: Add filesystem private data to mount points
## cherrypick kernel/common/mainline a618d31ac826e1624836e6fb7d5a2647b23ae6bb
## http://android-review.linaro.org/c/kernel/common/+/20494
#apply --linaro --local kernel/common/mainline --remote kernel/common 20494/3
## ANDROID: vfs: Allow filesystems to access their private mount data
## cherrypick kernel/common/mainline 8fd4c18e0b03376c61a0633c3630906b8dcb6497
## http://android-review.linaro.org/c/kernel/common/+/20495
#apply --linaro --local kernel/common/mainline --remote kernel/common 20495/1

## ANDROID: vfs: Add setattr2 for filesystems with per mount permissions
## cherrypick kernel/common/mainline 74cca90e7d2bd994696c1807362cd80fcca7dcb4
## https://android-review.googlesource.com/c/kernel/common/+/983024
apply --local kernel/common/mainline --remote kernel/common 983024/1

## ANDROID: vfs: Add permission2 for filesystems with per mount permissions
## cherrypick kernel/common/mainline e81cea2a6f86374194031a736b7139100c0b66c2
## https://android-review.googlesource.com/c/kernel/common/+/983025
apply --local kernel/common/mainline --remote kernel/common 983025/1

## ANDROID: vfs: add d_canonical_path for stacked filesystem support
## cherrypick kernel/common/mainline eb9e939dacee9e2422d62e9a8089e4ce4227ea64
## http://android-review.linaro.org/c/kernel/common/+/20493 ANDROID: vfs: add d_canonical_path for stacked filesystem support
## https://android-review.googlesource.com/c/kernel/common/+/983029
apply --local kernel/common/mainline --remote kernel/common 983029/1

## ANDROID: fs: Restore vfs_path_lookup() export
## cherrypick kernel/common/mainline c1d30dd04e5fadc8b0acd82144ae1ec4597846db
## https://android-review.googlesource.com/c/kernel/common/+/983026
apply --local kernel/common/mainline --remote kernel/common 983026/1

## ANDROID: sdcardfs: Define magic value
## cherrypick kernel/common/mainline 2105dc7a05dac5d355e5a6615167787f5637adc8
## https://android-review.googlesource.com/c/kernel/common/+/983027
apply --local kernel/common/mainline --remote kernel/common 983027/1

## ANDROID: sdcardfs: Add sdcardfs filesystem
## cherrypick kernel/common/mainline 874b34420a3473fabbd3694d2e6c5452886f12a6
## http://android-review.linaro.org/c/kernel/common/+/20496
## https://android-review.googlesource.com/c/kernel/common/+/983023
apply --local kernel/common/mainline --remote kernel/common 983023/3
