#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_amit_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="common"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/amit.pundir/linux.git/patch/?id=${commit_id} ${target_dir}
    fi
}

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="common"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} ${target_dir}
    fi
}
##################################################
################ Linaro hack   ###################
##################################################
## gki_defconfig & db845c_gki.fragment: initial commit
## http://android-review.linaro.org/c/kernel/common/+/21034
apply --linaro --local common --remote kernel/common 21034/4
apply --linaro --local kernel/common/mainline --remote kernel/common 21034/4

## phy: qcom-qmp: Increase PHY ready timeout
## https://git.linaro.org/people/amit.pundir/linux.git/commit/drivers/phy/qualcomm?h=dragonboard-android-mainline-tracking&id=df78c2a1026c0554cf7c3b9ede7485d214d0290f
apply_amit_mainline_patch df78c2a1026c0554cf7c3b9ede7485d214d0290f
## phy: qcom: qmp: Use power_on/off ops for PCIe
## https://git.linaro.org/people/amit.pundir/linux.git/commit/drivers/phy/qualcomm?h=dragonboard-android-mainline-tracking&id=1bceb86fca505b8e94654ac941ac408209d668b8
apply_amit_mainline_patch 1bceb86fca505b8e94654ac941ac408209d668b8
## phy: qcom: qmp: Add SDM845 PCIe QMP PHY support
## https://git.linaro.org/people/amit.pundir/linux.git/commit/drivers/phy/qualcomm?h=dragonboard-android-mainline-tracking&id=0102c668ff9605a2c56311ddb4709a51fdae4d63
apply_amit_mainline_patch 0102c668ff9605a2c56311ddb4709a51fdae4d63
## phy: qcom: qmp: Add SDM845 QHP PCIe PHY
## https://git.linaro.org/people/amit.pundir/linux.git/commit/drivers/phy/qualcomm?h=dragonboard-android-mainline-tracking&id=598e10c27e345f9a6a2e684faba949943c2bc1e4
apply_amit_mainline_patch 598e10c27e345f9a6a2e684faba949943c2bc1e4

## HACK: drm: msm: quiet down plane errors
## https://git.linaro.org/people/amit.pundir/linux.git/commit/drivers/gpu/drm/msm?h=dragonboard-android-mainline-tracking&id=589cb23b09e01d2395bccd3bf328fcce87ad29c4
apply_amit_mainline_patch 589cb23b09e01d2395bccd3bf328fcce87ad29c4

## DONTMERGE: clk: inherit clocks enabled by bootloader
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/clk?h=dev/db845c-v5.4-gki&id=8a68a12e0db9b2c65bf084965ae7ad289a77c623
apply_jstultz_mainline_patch 8a68a12e0db9b2c65bf084965ae7ad289a77c623

## ANDROID: PCI: qcom: Fix the fixup of PCI_VENDOR_ID_QCOM
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/include/linux?h=dev/db845c-v5.4-gki&id=be9286ef61dc41da161b82bebf866c829bd41c16
apply_jstultz_mainline_patch be9286ef61dc41da161b82bebf866c829bd41c16
## ANDROID: PCI: qcom: Add support for SDM845 PCIe controller
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/pci/controller/dwc/pcie-qcom.c?h=dev/db845c-v5.4-gki&id=d04dc51ef04f3bc26d5d1f64c30f0b710a9b7481
apply_jstultz_mainline_patch d04dc51ef04f3bc26d5d1f64c30f0b710a9b7481

## ANDORID: iommu: arm-smmu: Don't blindly use first SMR to calculate mask
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/iommu/arm-smmu.c?h=dev/db845c-v5.4-gki&id=0c3385706d1b6714aafbe4590730001e0917977e
## http://android-review.linaro.org/c/kernel/common/+/21028
apply --linaro --local common --remote kernel/common 21028/1
## ANDROID: iommu: arm-smmu: Handoff SMR registers and context banks
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/iommu/arm-smmu.c?h=dev/db845c-v5.4-gki&id=df98d3dfce3c26896361c2aad7a88ba46c7e36a6
## http://android-review.linaro.org/c/kernel/common/+/21029
apply --linaro --local common --remote kernel/common 21029/1

## usb: xhci: add firmware loader for uPD720201 and uPD720202 w/o ROM
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=8b67a5c0e83d685bd3024d90c7baf3f352dcc0e6
apply_jstultz_mainline_patch 8b67a5c0e83d685bd3024d90c7baf3f352dcc0e6
## usb: xhci: handle uPD720201 and uPD720202 w/o ROM
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=1e1db38cbd64d26bc8d7d784ada8b7de325d03eb
apply_jstultz_mainline_patch 1e1db38cbd64d26bc8d7d784ada8b7de325d03eb
## usb: xhci: Use register defined and field names
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=2ecb6c881ba10e99ca315466889b73688021f7c7
apply_jstultz_mainline_patch 2ecb6c881ba10e99ca315466889b73688021f7c7
## usb: xhci: Add ROM loader for uPD720201
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=55be4d14fe483d935dfa1b17309fe87a1375c43d
apply_jstultz_mainline_patch 55be4d14fe483d935dfa1b17309fe87a1375c43d
## usb: xhci: allow multiple firmware versions
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=f7d869b28a61fd1c8a9256dbeb01e9456e1183e5
apply_jstultz_mainline_patch f7d869b28a61fd1c8a9256dbeb01e9456e1183e5
## usb: xhci: provide a debugfs hook for erasing rom
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/host/xhci-pci.c?h=dev/db845c-v5.4-gki&id=e539422f1a5b64e593629ab3c517e90d35a9906b
apply_jstultz_mainline_patch e539422f1a5b64e593629ab3c517e90d35a9906b

## HACK: usb: dwc3: Disable sg_supported in order to avoid USB transfer errors
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/dwc3?h=dev/db845c-v5.4-gki&id=935277fc30c043c58fbe174cbbe208758d54c774
apply_jstultz_mainline_patch 935277fc30c043c58fbe174cbbe208758d54c774
