#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local dst_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        dst_dir="$1"
    fi

    if [ -d "${dst_dir}" ]; then
        curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} "${dst_dir}"
    else
        echo "${dst_dir} does not exist, skip to apply commit:${commit_id}"
    fi
}

##################################################
################ Linaro hack   ###################
##################################################
## gki: add hikey960_gki.fragment and udpate gki_defconfig for hikey960 [NEW]
## http://android-review.linaro.org/c/kernel/common/+/20887
apply --linaro --local kernel/common/mainline --remote kernel/common 20887/8

## DTS/hikey960_defconfig for hikey960 for android-mainline
## https://android-review.linaro.org/c/kernel/common/+/20669
apply --linaro --local kernel/common/mainline --remote kernel/common 20669/4

## Changes on DRM for hikey960 with android-mainline
# drm: kirin: Introduce kirin960
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=b21aad84e427c5555d8ef49fffec143a3704572f
# http://android-review.linaro.org/c/kernel/common/+/21069
apply --linaro --local kernel/common/mainline --remote kernel/common 21069/1
# drm: kirin: Add kirin960 dpe driver support
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=e37c6258e72753eac0704ddc02f33c67fca06241
# http://android-review.linaro.org/c/kernel/common/+/21071
apply --linaro --local kernel/common/mainline --remote kernel/common 21071/1
# drm: kirin: Remove LDI enable
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=559d18b4a55610bc68b43b76f816365e16d7d5ea
apply_jstultz_mainline_patch 559d18b4a55610bc68b43b76f816365e16d7d5ea
# drm: kirin: remove wait for VACTIVE IRQ
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=9dc3d350ef25c9f1e21963599d905050ad4e7214
apply_jstultz_mainline_patch 9dc3d350ef25c9f1e21963599d905050ad4e7214
# drm: kirin_drm_dpe: Fix rdma_stride calculation
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=bf3acc5a5d82896ca38def1c37f505b3f6fe034d
apply_jstultz_mainline_patch bf3acc5a5d82896ca38def1c37f505b3f6fe034d
# drm: kirin960: Remove one mode-line that seems to be causing trouble
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=8fa57fda3d9389df3a5a319c7b7e4527e45f7352
apply_jstultz_mainline_patch 8fa57fda3d9389df3a5a319c7b7e4527e45f7352
# drm: kirin960: Fix issue seen with HDMI hotplug
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=cd7e4b9a4b2d36e5be910df9f9c5f5e413467d09
apply_jstultz_mainline_patch cd7e4b9a4b2d36e5be910df9f9c5f5e413467d09
# drm: kirin: Fix Makefile to correct for module builds
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=c434e9009e2cdb0cb16916d636e3f0f5a0bdb67a
apply_jstultz_mainline_patch c434e9009e2cdb0cb16916d636e3f0f5a0bdb67a
# kirin_dpe build fix (fold down)
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=c002fc2bd41c90c173532cefdd02b2f7d35b34f3
apply_jstultz_mainline_patch c002fc2bd41c90c173532cefdd02b2f7d35b34f3

## Mali Source for HiKey960 for android-mainline
## https://android-review.linaro.org/c/kernel/common/+/20670
apply --linaro --local kernel/common/mainline --remote kernel/common 20670/5

## hikey960: Support usb functionality of Hikey960
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/misc?h=dev/hikey960-mainline-WIP&id=1c13c7737bbd61c67a7531d5c2db6e037e37a133
## http://android-review.linaro.org/c/kernel/common/+/20671
apply --linaro --local kernel/common/mainline --remote kernel/common 20671/1
## usb: dwc3: dwc3-of-simple: Add support for dwc3 of Hisilicon Soc Platform
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/dwc3/dwc3-of-simple.c?h=dev/hikey960-mainline-WIP&id=e7f71d8361d7b2e05e686f2a3767f557e3a342e7
apply_jstultz_mainline_patch e7f71d8361d7b2e05e686f2a3767f557e3a342e7
## usb: dwc3: Add splitdisable quirk for Hisilicon Kirin Soc
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/usb/dwc3?h=dev/gki-hikey960-android-mainline&id=8c8c937e33739704d49f75a63416d105e25a6040
## http://android-review.linaro.org/c/kernel/common/+/20862
apply --linaro --local kernel/common/mainline --remote kernel/common 20862/1
## usb: dwc3: Registering a role switch in the DRD code.
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=2d9ac7718ceade14df3ff775e71682883e212e0f
apply_jstultz_mainline_patch 2d9ac7718ceade14df3ff775e71682883e212e0f
## usb: roles: Add usb role switch notifier.
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/include/linux/usb?h=dev/hikey960-mainline-WIP&id=184fb435233887de2ab1c062141f291354861155
apply_jstultz_mainline_patch 184fb435233887de2ab1c062141f291354861155
## usb: dwc3: Kconfig: Don't force USB_ROLE_SWITCH from non-modular USB_DWC3_DUAL_ROLE
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/drivers/usb/dwc3/Kconfig?id=db3b6eaef3b3974108032d8c3ca577f38e4dcd61
apply_jstultz_mainline_patch db3b6eaef3b3974108032d8c3ca577f38e4dcd61
## usb: dwc3: Execute GCTL Core Soft Reset while switch mdoe for Hisilicon Kirin Soc
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/drivers/usb/dwc3/core.c?id=34cbbd42d380d1fbf1ab1de7f51d6dcb6bf5daae
apply_jstultz_mainline_patch 34cbbd42d380d1fbf1ab1de7f51d6dcb6bf5daae
## usb: dwc3: Increase timeout for CmdAct cleared by device controller
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/drivers/usb/dwc3/gadget.c?id=daeea2e203a38e1c9f67f506cdafb643cd977f8d
apply_jstultz_mainline_patch daeea2e203a38e1c9f67f506cdafb643cd977f8d
## usb: gadget: Add configfs attribuite for controling match_existing_only
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/drivers/usb/gadget/configfs.c?id=729fd81cf8fdf097861b58f73dd3e8110204bffd
apply_jstultz_mainline_patch 729fd81cf8fdf097861b58f73dd3e8110204bffd
## reset: hisi-reboot: adb reboot bootloader
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/power/reset?h=dev/hikey960-mainline-WIP&id=fe671288fa7ad845e525149d6e4686b692926ff8
apply_jstultz_mainline_patch fe671288fa7ad845e525149d6e4686b692926ff8

## sound: Add hikey960 i2s audio driver
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey960-mainline-WIP&id=6c6b0dc021299303751dc930d9ec1c8abf2c641f
apply_jstultz_mainline_patch 6c6b0dc021299303751dc930d9ec1c8abf2c641f

## fix: bluetooth: hci_ll: set enable_gpio direction OUT at probe
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/drivers/bluetooth/hci_ll.c?id=1f1a6cc78f0a4c17033fec3d6582f8d6ba0781cb
apply_jstultz_mainline_patch 1f1a6cc78f0a4c17033fec3d6582f8d6ba0781cb

## hisi_hikey_usb: Fix of_match_table referecne to fix module loading
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/drivers/misc/hisi_hikey_usb.c?id=fe2bd836fbe11e0e23b997e1f5a61ec5077e6da3
apply_jstultz_mainline_patch fe2bd836fbe11e0e23b997e1f5a61ec5077e6da3

## HACK: Allow hisi-reboot to be a module
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/drivers/power/reset?id=c23cb6dfc2fd086f6d4cec5ba392dc19a156e3e9
apply_jstultz_mainline_patch c23cb6dfc2fd086f6d4cec5ba392dc19a156e3e9

## reset: hi6220: Add support for AO reset controller
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/drivers/reset/hisilicon/hi6220_reset.c?id=3c2129f92e239d98326608951e815fd413f3ebc6
apply_jstultz_mainline_patch 3c2129f92e239d98326608951e815fd413f3ebc6
