#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local dst_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        dst_dir="$1"
    fi

    if [ -d "${dst_dir}" ]; then
        curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} "${dst_dir}"
    else
        echo "${dst_dir} does not exist, skip to apply commit:${commit_id}"
    fi
}

function apply_android_review_mainline_patch(){
    local commit_id=$1 && shift
    local dst_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        dst_dir="$1"
    fi

    if [ -d "${dst_dir}" ]; then
        curl_am https://android-git.linaro.org/kernel/common.git/patch/?id=${commit_id} "${dst_dir}"
    else
        echo "${dst_dir} does not exist, skip to apply commit:${commit_id}"
    fi
}
##################################################
################ Linaro hack   ###################
##################################################
## gki: add hikey960_gki.fragment and udpate gki_defconfig for hikey960 [NEW]
## http://android-review.linaro.org/c/kernel/common/+/20887
apply --linaro --local kernel/common/mainline --remote kernel/common 20887/12

## DTS/hikey960_defconfig for hikey960 for android-mainline
## https://android-review.linaro.org/c/kernel/common/+/20669
apply --linaro --local kernel/common/mainline --remote kernel/common 20669/4

## Changes on DRM for hikey960 with android-mainline
# drm: kirin: Introduce kirin960
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon?h=dev/hikey960-mainline-WIP&id=ac560df58a729ef5169c6e7bc1e2867f37c6ad71
apply_jstultz_mainline_patch ac560df58a729ef5169c6e7bc1e2867f37c6ad71
# ANDROID: drm: kirin: fix export symbol type
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon?h=dev/hikey960-mainline-WIP&id=a06639f8dacb3c583dc3da5b0f4eb41b24e96970
apply_jstultz_mainline_patch a06639f8dacb3c583dc3da5b0f4eb41b24e96970
# drm: kirin: Add kirin960 dpe driver support
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon?h=dev/hikey960-mainline-WIP&id=72487cabff3783bc609836da9c2301dff4271fbd
apply_jstultz_mainline_patch 72487cabff3783bc609836da9c2301dff4271fbd
# drm: kirin: remove wait for VACTIVE IRQ
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon?h=dev/hikey960-mainline-WIP&id=fa1ab50507e116e72b23cfe41d27ef6c62d6f63d
apply_jstultz_mainline_patch fa1ab50507e116e72b23cfe41d27ef6c62d6f63d
# drm: kirin_drm_dpe: Fix rdma_stride calculation
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon?h=dev/hikey960-mainline-WIP&id=64a87050f5f4886e4a21021d85796058bb9b0ee5
apply_jstultz_mainline_patch 64a87050f5f4886e4a21021d85796058bb9b0ee5
# drm: kirin960: Remove one mode-line that seems to be causing trouble
# https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon?h=dev/hikey960-mainline-WIP&id=15a28b2666c49575f63b022c32d844a0a3fb05dc
apply_jstultz_mainline_patch 15a28b2666c49575f63b022c32d844a0a3fb05dc

## Mali Source for HiKey960 for android-mainline
## https://android-review.linaro.org/c/kernel/common/+/20670
apply --linaro --local kernel/common/mainline --remote kernel/common 20670/9

## misc: hisi_hikey_usb: Driver to support onboard USB gpio hub on Hikey960
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=d369b15e4f0485de1e4b3fd50e66696bd5b407bf
## http://android-review.linaro.org/c/kernel/common/+/21381
apply --linaro --local kernel/common/mainline --remote kernel/common 21381/1
## reset: hisi-reboot: adb reboot bootloader
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/power/reset?h=dev/hikey960-mainline-WIP&id=fe671288fa7ad845e525149d6e4686b692926ff8
apply_jstultz_mainline_patch fe671288fa7ad845e525149d6e4686b692926ff8

## sound: Add hikey960 i2s audio driver
## https://android-git.linaro.org/kernel/common.git/patch/?id=2d6e446fde0abe2ee1425f745a23e5f2b3ad1736
apply_android_review_mainline_patch 2d6e446fde0abe2ee1425f745a23e5f2b3ad1736

## fix: bluetooth: hci_ll: set enable_gpio direction OUT at probe
## https://android-git.linaro.org/kernel/common.git/commit/?h=android-mainline-gki-hikey960&id=01f917927efca505bb8e31901a89ee2fa71d73e7
apply_android_review_mainline_patch 01f917927efca505bb8e31901a89ee2fa71d73e7

######### temporary workarounds for sdcardfs ##################
## ANDROID: vfs: Add setattr2 for filesystems with per mount permissions
apply --linaro --local kernel/common/mainline --remote kernel/common 21553/2
## ANDROID: vfs: Add permission2 for filesystems with per mount permissions
apply --linaro --local kernel/common/mainline --remote kernel/common 21554/4
## ANDROID: vfs: add d_canonical_path for stacked filesystem support
apply --linaro --local kernel/common/mainline --remote kernel/common 21555/1
## ANDROID: fs: Restore vfs_path_lookup() export
apply --linaro --local kernel/common/mainline --remote kernel/common 21556/1
## ANDROID: sdcardfs: remove sdcardfs from system
apply --linaro --local kernel/common/mainline --remote kernel/common 21557/1
