#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local dst_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        dst_dir="$1"
    fi

    if [ -d "${dst_dir}" ]; then
        curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} "${dst_dir}"
    else
        echo "${dst_dir} does not exist, skip to apply commit:${commit_id}"
    fi
}

function apply_android_review_mainline_patch(){
    local commit_id=$1 && shift
    local dst_dir="kernel/common/mainline"
    if [ -n "$1" ]; then
        dst_dir="$1"
    fi

    if [ -d "${dst_dir}" ]; then
        curl_am https://android-git.linaro.org/kernel/common.git/patch/?id=${commit_id} "${dst_dir}"
    else
        echo "${dst_dir} does not exist, skip to apply commit:${commit_id}"
    fi
}
##################################################
################ Linaro hack   ###################
##################################################
## gki: add hikey960_gki.fragment and udpate gki_defconfig for hikey960 [NEW]
## http://android-review.linaro.org/c/kernel/common/+/20887
apply --linaro --local kernel/common/mainline --remote kernel/common 20887/12

## DTS/hikey960_defconfig for hikey960 for android-mainline
## dts: Add usb mux hub for hikey960
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/arch/arm64/boot/dts/hisilicon?h=dev/hikey960-mainline-WIP&id=2c5bf10b5a15605f0f3c3a5302168c746554b245
## http://android-review.linaro.org/c/kernel/common/+/21678
apply --linaro --local kernel/common/mainline --remote kernel/common 21678/1
## arm64: dts: hikey960: Add CMA entry for ION/framebuffers
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/arch/arm64/boot/dts/hisilicon?h=dev/hikey960-mainline-WIP&id=7557b48e2481afb2cb37e0118d4225d482372b7e
## http://android-review.linaro.org/c/kernel/common/+/21679
apply --linaro --local kernel/common/mainline --remote kernel/common 21679/1
## arm64: dts: hi3660: add display driver dts
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/arch/arm64/boot/dts/hisilicon?h=dev/hikey960-mainline-WIP&id=6223a576d20c5aad7e812c43c66e338207d1a44e
## http://android-review.linaro.org/c/kernel/common/+/21680
apply --linaro --local kernel/common/mainline --remote kernel/common 21680/1
## arm64: dts: hi3660-hikey960: Add i2s & sound device
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/arch/arm64/boot/dts/hisilicon?h=dev/hikey960-mainline-WIP&id=2b8b1b008d2e1e0f4f879bc048daf11b0398023d
## http://android-review.linaro.org/c/kernel/common/+/21681
apply --linaro --local kernel/common/mainline --remote kernel/common 21681/1
## arm64: dts: enable gpu
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/arch/arm64/boot/dts/hisilicon?h=dev/hikey960-mainline-WIP&id=8e7479fec60803fc59f602216db4e7b0bbae6065
## http://android-review.linaro.org/c/kernel/common/+/21682
apply --linaro --local kernel/common/mainline --remote kernel/common 21682/1
## dts: Add pmctrl entry
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/arch/arm64/boot/dts/hisilicon?h=dev/hikey960-mainline-WIP&id=1798e274fb5ae20a734d6c4a3326c406f272b0b7
## http://android-review.linaro.org/c/kernel/common/+/21683
apply --linaro --local kernel/common/mainline --remote kernel/common 21683/1
## arm64: dts: hi3660: adb reboot node
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/arch/arm64/boot/dts/hisilicon?h=dev/hikey960-mainline-WIP&id=7280d580f225328079f105d9d954b361b7252279
## http://android-review.linaro.org/c/kernel/common/+/21684
apply --linaro --local kernel/common/mainline --remote kernel/common 21684/1
## dts: hikey960: Fix bootwarning on mapping reboot reason syscon
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/arch/arm64/boot/dts/hisilicon?h=dev/hikey960-mainline-WIP&id=6abecb74daab9e9b2e47851c110127c03eabfa1a
## http://android-review.linaro.org/c/kernel/common/+/21685
apply --linaro --local kernel/common/mainline --remote kernel/common 21685/1

## Changes on DRM for hikey960 with android-mainline
## drm: kirin: Introduce kirin960
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon/kirin?h=dev/hikey960-mainline-WIP&id=8003041caae7c8c3b3917953c604b5eb1deef2ac
## http://android-review.linaro.org/c/kernel/common/+/21069
apply --linaro --local kernel/common/mainline --remote kernel/common 21069/4
## ANDROID: drm: kirin: fix export symbol type
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon/kirin?h=dev/hikey960-mainline-WIP&id=56504c624176170aca2139465588b6ee214fd239
## http://android-review.linaro.org/c/kernel/common/+/21672
apply --linaro --local kernel/common/mainline --remote kernel/common 21672/1
## drm: kirin: Add kirin960 dpe driver support
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon/kirin?h=dev/hikey960-mainline-WIP&id=583c136a98b70e12a373d780980d36d7f0caaf5a
## http://android-review.linaro.org/c/kernel/common/+/21071
apply --linaro --local kernel/common/mainline --remote kernel/common 21071/2
## drm: kirin: remove wait for VACTIVE IRQ
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon/kirin?h=dev/hikey960-mainline-WIP&id=86c382c3e1d68ebc1d80bf3d432206ce66933a43
## http://android-review.linaro.org/c/kernel/common/+/21673
apply --linaro --local kernel/common/mainline --remote kernel/common 21673/1
## drm: kirin_drm_dpe: Fix rdma_stride calculation
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon/kirin?h=dev/hikey960-mainline-WIP&id=f9783dafe35c909fd01d6064a989442c07857c73
## http://android-review.linaro.org/c/kernel/common/+/21674
apply --linaro --local kernel/common/mainline --remote kernel/common 21674/1
## drm: kirin960: Remove one mode-line that seems to be causing trouble
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm/hisilicon/kirin?h=dev/hikey960-mainline-WIP&id=6cfdd43e72d1b146ee311d6080c1fdfadc525d8c
## http://android-review.linaro.org/c/kernel/common/+/21675
apply --linaro --local kernel/common/mainline --remote kernel/common 21675/1
## HACK: adv7511: Add poweron delay to allow for EDID probing to work
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/gpu/drm?h=dev/hikey960-mainline-WIP&id=20572af2f4123ffc8e0ab64db2b6029ce8f727bd
## http://android-review.linaro.org/c/kernel/common/+/21676
apply --linaro --local kernel/common/mainline --remote kernel/common 21676/1

## Mali Source for HiKey960 for android-mainline
## https://android-review.linaro.org/c/kernel/common/+/20670
apply --linaro --local kernel/common/mainline --remote kernel/common 20670/9

## misc: hisi_hikey_usb: Driver to support onboard USB gpio hub on Hikey960
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/misc/hisi_hikey_usb.c?h=dev/hikey960-mainline-WIP&id=33bdae00879e78e13897cd50eab92600f2fc737d
## http://android-review.linaro.org/c/kernel/common/+/21381
apply --linaro --local kernel/common/mainline --remote kernel/common 21381/1
## reset: hisi-reboot: adb reboot bootloader
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/drivers/power/reset?h=dev/hikey960-mainline-WIP&id=fe671288fa7ad845e525149d6e4686b692926ff8
apply_jstultz_mainline_patch fe671288fa7ad845e525149d6e4686b692926ff8

## sound: Add hikey960 i2s audio driver
## https://android-git.linaro.org/kernel/common.git/patch/?id=2d6e446fde0abe2ee1425f745a23e5f2b3ad1736
apply_android_review_mainline_patch 2d6e446fde0abe2ee1425f745a23e5f2b3ad1736

## fix: bluetooth: hci_ll: set enable_gpio direction OUT at probe
## https://android-git.linaro.org/kernel/common.git/commit/?h=android-mainline-gki-hikey960&id=01f917927efca505bb8e31901a89ee2fa71d73e7
apply_android_review_mainline_patch 01f917927efca505bb8e31901a89ee2fa71d73e7

######### temporary workarounds for sdcardfs ##################
## ANDROID: vfs: Add setattr2 for filesystems with per mount permissions
apply --linaro --local kernel/common/mainline --remote kernel/common 21553/4
## ANDROID: vfs: Add permission2 for filesystems with per mount permissions
apply --linaro --local kernel/common/mainline --remote kernel/common 21554/6
## ANDROID: vfs: add d_canonical_path for stacked filesystem support
## https://android-review.linaro.org/c/kernel/common/+/21555
apply --linaro --local kernel/common/mainline --remote kernel/common 21555/4
## ANDROID: fs: Restore vfs_path_lookup() export
## https://android-review.linaro.org/c/kernel/common/+/21556
apply --linaro --local kernel/common/mainline --remote kernel/common 21556/3
## ANDROID: sdcardfs: remove sdcardfs from system
apply --linaro --local kernel/common/mainline --remote kernel/common 21557/3
## ANDROID: fscrypt: add key removal notifier chain
apply --linaro --local kernel/common/mainline --remote kernel/common 21612/2
## Revert "Revert "ANDROID: mnt: Add filesystem private data to mount points""
## http://android-review.linaro.org/c/kernel/common/+/21705
apply --linaro --local kernel/common/mainline --remote kernel/common 21705/1
## Revert "Revert "ANDROID: mnt: Fix null pointer dereference""
## http://android-review.linaro.org/c/kernel/common/+/21706
apply --linaro --local kernel/common/mainline --remote kernel/common 21706/1
## Revert "Revert "ANDROID: Add show_options2 to view private mount data""
## http://android-review.linaro.org/c/kernel/common/+/21707
apply --linaro --local kernel/common/mainline --remote kernel/common 21707/1
