#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} kernel/common/mainline
}

##################################################
################ Linaro hack   ###################
##################################################
## add hikey_gki.fragment for gki build
## https://android-review.linaro.org/c/kernel/common/+/20784/
apply --linaro --local kernel/common/mainline --remote kernel/common 20784/20

## revert clk: hi6220: use CLK_OF_DECLARE_DRIVER
revert kernel/common/mainline f1edb498bd9f25936ae3540a8dbd86e6019fdb95
revert common f1edb498bd9f25936ae3540a8dbd86e6019fdb95

## drm: kirin: Tweak the LDI handling
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=f8b62fd328606c51e4f96edf517f02af889bc7ed
apply_jstultz_mainline_patch f8b62fd328606c51e4f96edf517f02af889bc7ed
## another try at LDI fix
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=daabc8301e90f1b4ec4ebbd8b36cda7838918a02
apply_jstultz_mainline_patch daabc8301e90f1b4ec4ebbd8b36cda7838918a02
