#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} kernel/common/mainline
}

##################################################
################ Linaro hack   ###################
##################################################
## HACK: dts: hi6220: Add special mali utgard driver dts properties
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey-mainline-WIP&id=6df17351c943d3bfde90a918f318a80931fcee12
apply_jstultz_mainline_patch 6df17351c943d3bfde90a918f318a80931fcee12

## mali source to compile it as a kernel module
## Merge of mali related changes for mainline for hikey
## https://android-review.linaro.org/c/kernel/common/+/20652
apply --linaro --local kernel/common/mainline --remote kernel/common 20652/4
