#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} kernel/common/mainline
}

##################################################
################ Linaro hack   ###################
##################################################
## enable overlay manager to boot
## http://android-review.linaro.org/c/kernel/common/+/20471
apply --linaro --local kernel/common/mainline --remote kernel/common 20471/2

## mali source to compile it as a kernel module
## http://android-review.linaro.org/c/kernel/common/+/20472
apply --linaro --local kernel/common/mainline --remote kernel/common 20472/2

## HACK: MALI: 4.20-rc fix to use vmf_insert_pfn
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=8a9ad8e33b44cec6c209d9894eb665011ed014fb
apply_jstultz_mainline_patch 8a9ad8e33b44cec6c209d9894eb665011ed014fb

## MALI: 4.20-rc time fixup
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=4f517b3fa9c150e015e2eebfbf68c6c1f02738cc
apply_jstultz_mainline_patch 4f517b3fa9c150e015e2eebfbf68c6c1f02738cc

## MALI: Build fixup for 5.1-rc on using vm_fault_t
## https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=d824e645c2a64c695cff6ccb4718d03acc14a1d2
apply_jstultz_mainline_patch d824e645c2a64c695cff6ccb4718d03acc14a1d2

## MALI: access_ok fix for 5.0-rc
## https://git.linaro.org/people/john.stultz/android-dev.git/patch?id=c9d871991a5d3b9a8a6c66dd97f77a53ca6c80e0
apply_jstultz_mainline_patch c9d871991a5d3b9a8a6c66dd97f77a53ca6c80e0

## HACK: usb: dwc2: Disable sg_supported on gadget
## https://git.linaro.org/people/john.stultz/android-dev.git/commit/?h=dev/hikey-mainline-WIP&id=248fc0d31f793c268078e8227310f91677943a03
apply_jstultz_mainline_patch 248fc0d31f793c268078e8227310f91677943a03

## Revert "security: Implement Clang's stack initialization"
revert kernel/common/mainline 709a972efb01efaeb97cad1adc87fe400119c8ab

## Revert "arm64: Silence gcc warnings about arch ABI drift"
## To workaround the undefined reference to `__efistub___stack_chk_guard' problem
## reported here: https://ci.linaro.org/job/lkft-android-9.0-mainline/7/console
revert kernel/common/mainline ebcc5928c5d925b1c8d968d9c89cdb0d0186db17

############### support for sdcardfs ====================================
## need for cts test, otherwise "Device must have external storage mounted in order to run CTS" will be reported
## ANDROID: sdcardfs: Enable modular sdcardfs
## http://android-review.linaro.org/c/kernel/common/+/20492
## cherrypick kernel/common/mainline 50f0dd432bf59a71ac8c246b14de2e17701b3ab9
## https://android-review.googlesource.com/c/kernel/common/+/983028
apply --local kernel/common/mainline --remote kernel/common 983028/1

## ANDROID: mnt: Add filesystem private data to mount points
## cherrypick kernel/common/mainline a618d31ac826e1624836e6fb7d5a2647b23ae6bb
## http://android-review.linaro.org/c/kernel/common/+/20494
#apply --linaro --local kernel/common/mainline --remote kernel/common 20494/3
## ANDROID: vfs: Allow filesystems to access their private mount data
## cherrypick kernel/common/mainline 8fd4c18e0b03376c61a0633c3630906b8dcb6497
## http://android-review.linaro.org/c/kernel/common/+/20495
#apply --linaro --local kernel/common/mainline --remote kernel/common 20495/1

## ANDROID: vfs: Add setattr2 for filesystems with per mount permissions
## cherrypick kernel/common/mainline 74cca90e7d2bd994696c1807362cd80fcca7dcb4
## https://android-review.googlesource.com/c/kernel/common/+/983024
apply --local kernel/common/mainline --remote kernel/common 983024/1

## ANDROID: vfs: Add permission2 for filesystems with per mount permissions
## cherrypick kernel/common/mainline e81cea2a6f86374194031a736b7139100c0b66c2
## https://android-review.googlesource.com/c/kernel/common/+/983025
apply --local kernel/common/mainline --remote kernel/common 983025/1

## ANDROID: vfs: add d_canonical_path for stacked filesystem support
## cherrypick kernel/common/mainline eb9e939dacee9e2422d62e9a8089e4ce4227ea64
## http://android-review.linaro.org/c/kernel/common/+/20493 ANDROID: vfs: add d_canonical_path for stacked filesystem support
## https://android-review.googlesource.com/c/kernel/common/+/983029
apply --local kernel/common/mainline --remote kernel/common 983029/1

## ANDROID: fs: Restore vfs_path_lookup() export
## cherrypick kernel/common/mainline c1d30dd04e5fadc8b0acd82144ae1ec4597846db
## https://android-review.googlesource.com/c/kernel/common/+/983026
apply --local kernel/common/mainline --remote kernel/common 983026/1

## ANDROID: sdcardfs: Define magic value
## cherrypick kernel/common/mainline 2105dc7a05dac5d355e5a6615167787f5637adc8
## https://android-review.googlesource.com/c/kernel/common/+/983027
apply --local kernel/common/mainline --remote kernel/common 983027/1

## ANDROID: sdcardfs: Add sdcardfs filesystem
## cherrypick kernel/common/mainline 874b34420a3473fabbd3694d2e6c5452886f12a6
## http://android-review.linaro.org/c/kernel/common/+/20496
## https://android-review.googlesource.com/c/kernel/common/+/983023
apply --local kernel/common/mainline --remote kernel/common 983023/1
