#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

function apply_jstultz_mainline_patch(){
    local commit_id=$1 && shift
    local target_dir="common"
    if [ -n "$1" ]; then
        target_dir=$1 && shift
    fi
    if [ -d ${target_dir} ]; then
        curl_am https://git.linaro.org/people/john.stultz/android-dev.git/patch/?id=${commit_id} ${target_dir}
    fi
}

function apply_x15_mainline_patch(){
    local commit_id=$1 && shift
    # https://android-git.linaro.org/kernel/common.git/patch/?id=29c3a9780ac275750a8ae664f31c3434b30ddc02
    curl_am https://android-git.linaro.org/kernel/common.git/patch/?id=${commit_id} kernel/common/mainline
}

##################################################
################    ###################
##################################################
## "opp: Allow dev_pm_opp_get_opp_table() to return -EPROBE_DEFER"
## https://www.spinics.net/lists/arm-kernel/msg849382.html
revert kernel/common/mainline dd461cd9183fe80bee84fd6cab2a29bfc8f55a76

## arch: arm: Enable SGX in device tree
## https://android-git.linaro.org/kernel/common.git/commit/?h=refs/heads/android-mainline-x15&id=1c59b34663f25385ea3ff288dba549f290db5e34
## http://android-review.linaro.org/c/kernel/common/+/20521
apply --linaro --local kernel/common/mainline --remote kernel/common 20521/5
