#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################
# Include bionic tests patch http://review.android.git.linaro.org/#/c/15288/
apply --linaro system/extras 15288/2

##################################################
################ Backport ########################
##################################################
# Include fix for monkey crash on browser package:
# https://android-review.googlesource.com/#/c/118963
apply packages/apps/Browser 118963/1
# Fix Java detection on Linux distributions that
# rely on update-alternatives to allow several JDKs
# to coexist
cherrypick build 311384fec340a7f2f76ca7f45599987df4341d5b
# Allow the Denver implementation of memset to build
# with clang
cherrypick bionic ce46f5576ad0c9aefd842492949c4d2965e23e89
# Allow Bionic to build with clang
apply --linaro bionic 15515/1
# Allow skia to build with giflib 5.1
apply external/skia 151010/1

##################################################
################## Bug fixes #####################
##################################################
# Uninitialized variable
apply --linaro external/bluetooth/bluedroid 15610/1
# Fix API check on build hosts with modern glibc versions
apply system/core 114555/1
# Make sure HAVE_MALLOC_H has a value to make updated sqlite happy
cherrypick build 9b44afb4529d743e291d6565d6fbe463cd8c964b

##################################################
################ Temporary fix ###################
##################################################
# Include patch for start and stop file path for bootchart:
# https://android-review.googlesource.com/#/c/117071/
apply --linaro system/core 15367/2
apply --linaro external/sepolicy 15506/1

# patch to integrate tjbench test on jpeg project
apply --linaro external/jpeg 15791/1

##################################################
#### Optimizations not yet submitted upstream ####
##################################################

########################################################
#### Backports of optimizations submitted to master ####
########################################################

##################################################
################ Linaro hack   ###################
##################################################
