#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################
# Include bionic tests patch http://review.android.git.linaro.org/#/c/15288/
apply --linaro system/extras 15288/2

##################################################
################ Backport ########################
##################################################
# Include fix for monkey crash on browser package:
# https://android-review.googlesource.com/#/c/118963
apply packages/apps/Browser 118963/1
# Fix Java detection on Linux distributions that
# rely on update-alternatives to allow several JDKs
# to coexist
cherrypick build 311384fec340a7f2f76ca7f45599987df4341d5b
# Allow the Denver implementation of memset to build
# with clang
cherrypick bionic ce46f5576ad0c9aefd842492949c4d2965e23e89
# Allow Bionic to build with clang
apply --linaro bionic 15515/1
# Allow skia to build with giflib 5.1
apply external/skia 151010/1

##################################################
################## Bug fixes #####################
##################################################
# Uninitialized variable
apply --linaro external/bluetooth/bluedroid 15610/1
# Fix API check on build hosts with modern glibc versions
apply system/core 114555/1
# Make sure HAVE_MALLOC_H has a value to make updated sqlite happy
cherrypick build 9b44afb4529d743e291d6565d6fbe463cd8c964b

##################################################
################ Temporary fix ###################
##################################################
# Include patch for start and stop file path for bootchart:
# https://android-review.googlesource.com/#/c/117071/
apply --linaro system/core 15367/2
apply --linaro external/sepolicy 15506/1

##################################################
#### Optimizations not yet submitted upstream ####
##################################################
# Add optimizations from cortex-string for bionic
apply --linaro bionic 15494/5
apply --linaro bionic 15528/1
apply --linaro bionic 15529/1
# Further Bionic optimizations
apply --linaro bionic 15553/1
apply --linaro bionic 15566/1

########################################################
#### Backports of optimizations submitted to master ####
########################################################
apply --linaro bionic 15972/2

##################################################
################ Linaro hack   ###################
##################################################
# changes to make perf work on Lollipop
apply --linaro bionic 15845/3
apply --linaro external/elfutils 15844/2
apply --linaro external/linux-tools-perf 15843/2

# changes to make chromium_org to use the system libjpeg.so
apply --linaro external/chromium_org 15874/1
apply --linaro external/chromium_org/v8 15876/1
apply --linaro external/chromium_org/third_party/angle 15877/1
apply --linaro external/chromium_org/third_party/freetype 15878/1
apply --linaro external/chromium_org/third_party/icu 15879/1
apply --linaro external/chromium_org/third_party/libsrtp 15880/1
apply --linaro external/chromium_org/third_party/libvpx 15886/1
apply --linaro external/chromium_org/third_party/libyuv 15881/1
apply --linaro external/chromium_org/third_party/openmax_dl 15882/1
apply --linaro external/chromium_org/third_party/ots 15883/1
apply --linaro external/chromium_org/third_party/WebKit 15884/1
apply --linaro external/chromium_org/third_party/webrtc 15885/1

# changes to make chromium_org to use the system libz.so and libz_minizip.so
apply --linaro frameworks/webview 15973/1
apply --linaro external/zlib 15955/5
apply --linaro external/chromium_org 15960/5
apply --linaro external/chromium_org/third_party/ots 15957/2
apply --linaro external/chromium_org/third_party/freetype 15958/1
apply --linaro external/chromium_org/third_party/WebKit 15959/2
apply --linaro frameworks/base 15963/1
apply --linaro external/zlib 15978/1
apply --linaro external/chromium_org 15980/1
