#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

# changes to make chromium_org to use the system libjpeg.so
apply --linaro external/chromium_org 15874/1
apply --linaro external/chromium_org/v8 15876/1
apply --linaro external/chromium_org/third_party/angle 15877/1
apply --linaro external/chromium_org/third_party/freetype 15878/1
apply --linaro external/chromium_org/third_party/icu 15879/1
apply --linaro external/chromium_org/third_party/libsrtp 15880/1
apply --linaro external/chromium_org/third_party/libvpx 15886/1
apply --linaro external/chromium_org/third_party/libyuv 15881/1
apply --linaro external/chromium_org/third_party/openmax_dl 15882/1
apply --linaro external/chromium_org/third_party/ots 15883/1
apply --linaro external/chromium_org/third_party/WebKit 15884/1
apply --linaro external/chromium_org/third_party/webrtc 15885/1

# changes to make chromium_org to use the system libz.so and libz_minizip.so
apply --linaro frameworks/webview 15973/1
apply --linaro external/zlib 15955/5
apply --linaro external/chromium_org 15960/5
apply --linaro external/chromium_org/third_party/ots 15957/2
apply --linaro external/chromium_org/third_party/freetype 15958/1
apply --linaro external/chromium_org/third_party/WebKit 15959/2
