#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################
# patch to make 32bit binary on 64bit platforms use
# the existing assembly code for arm as well
# https://android-review.linaro.org/#/c/16238/
apply --linaro frameworks/av 16238/1

##################################################
################ Backport ########################
##################################################

##################################################
################## Bug fixes #####################
##################################################

##################################################
################ Temporary fix ###################
##################################################
# patch to integrate tjbench test on jpeg project
# https://android-review.linaro.org/#/c/15791/
apply --linaro external/jpeg 15791/1

##################################################
#### Optimizations not yet submitted upstream ####
##################################################
# Cortex-A57 support in Bionic
# https://android-review.linaro.org/#/c/16260/
apply --linaro bionic 16260/1
# ... and in ART
# https://android-review.linaro.org/#/c/16262/
apply --linaro art 16262/1

########################################################
#### Backports of optimizations submitted to master ####
########################################################

##################################################
################ Linaro hack   ###################
##################################################
