#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

# Add kludge for Pixel C keyboard layout support that made it to 6.0.1_r5 but not 6.0.1_r10
cherrypick frameworks/base f3ec536edbad295303d9a3cf80bd72a4675cf7c7
