#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

# Allow host tools to build with both OpenJDK 7 and OpenJDK 8
apply --linaro external/guava 16903/1

# Allow frameworks/support/v4 to find its dependencies
apply --linaro frameworks/support 17863/1
