#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

####################################################################
################ Workaround for using master clang  ################
####################################################################
## cc/config/clang.go: workaround for using master clang for AOSP master
## http://android-review.linaro.org/17791
apply --linaro build/soong 17791/1

## verify-asm-support: workaround for using master clang for AOSP master
## http://android-review.linaro.org/17792
apply --linaro art 17792/1
