#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################

##################################################
################ Backport ########################
##################################################
## Workaround for wallpaper not shown correctly problem
apply --linaro frameworks/base 17696/1

## Bootchart parse command
## http://android-review.linaro.org/17731
apply --linaro system/core 17731/6

## add cts-lkft plan
## https://android-review.linaro.org/#/c/platform/test/suite_harness/+/19623/
apply --linaro test/suite_harness 19623/1

## https://android-review.googlesource.com/c/platform/frameworks/opt/telephony/+/1090935
## PhoneSwitcher.java: add check for mPreferredDataPhoneId
apply frameworks/opt/telephony 1090935/1

## PhoneSwitcher.java: create a common function for getting phoneId with subId
## https://android-review.googlesource.com/c/platform/frameworks/opt/telephony/+/1090936
apply frameworks/opt/telephony 1090936/1
