#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi


##################################################
################ Linaro hack   ###################
##################################################
apply --linaro device/htc/flounder 15932/3
apply --linaro device/htc/flounder 16130/1
apply --linaro device/htc/flounder 16814/2
apply --linaro frameworks/base 16132/1
