#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################

##################################################
################ Backport ########################
##################################################
## Don't crash when displaying the " key
## https://android-review.googlesource.com/#/c/platform/packages/inputmethods/LatinIME/+/469478/
apply packages/inputmethods/LatinIME 469478/1

## CommandListener.cpp:  ensures to sort interfaces in alphabetical order
## http://android-review.linaro.org/17547
apply --linaro system/netd 17547/1

## Workaround for wallpaper not shown correctly problem
apply --linaro frameworks/base 17696/1

## Bootchart parse command
## http://android-review.linaro.org/17827
apply --linaro system/core 17827/2

## system_server: allow writing to timerslack_ns
## https://android.googlesource.com/platform/system/sepolicy/+/5c41d40ecd3558d44861374c1c490676a224b488
cherrypick system/sepolicy 5c41d40ecd3558d44861374c1c490676a224b488

## rootdir/etc/hosts: support dns resolution for loopback46.unittest.grpc.io
## http://android-review.linaro.org/17975
apply --linaro system/core 17975/2
