#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################

##################################################
################ Backport ########################
##################################################
## Don't crash when displaying the " key
## https://android-review.googlesource.com/#/c/platform/packages/inputmethods/LatinIME/+/469478/
apply packages/inputmethods/LatinIME 469478/1

## CommandListener.cpp:  ensures to sort interfaces in alphabetical order
## http://android-review.linaro.org/17547
apply --linaro system/netd 17547/1

## Workaround for wallpaper not shown correctly problem
apply --linaro frameworks/base 17696/1

## Bootchart parse command
## http://android-review.linaro.org/17827
apply --linaro system/core 17827/2

## system_server: allow writing to timerslack_ns
## https://android.googlesource.com/platform/system/sepolicy/+/5c41d40ecd3558d44861374c1c490676a224b488
cherrypick system/sepolicy 5c41d40ecd3558d44861374c1c490676a224b488

## rootdir/etc/hosts: support dns resolution for loopback46.unittest.grpc.io
## http://android-review.linaro.org/17975
apply --linaro system/core 17975/2

## sf: Initialize DispSync in SurfaceFlinger_hwc1
## which fixed the problem of "W SurfaceFlinger: Timed out waiting for hw vsync; faking it"
## for devices when swithce to use with 8.1.0_r1
## https://android-review.googlesource.com/c/platform/frameworks/native/+/519520
cherrypick frameworks/native c9d2db18d8154ef527dbf4d34c7bb3317bbdc98c

## Fix sanitizer in InputFlinger Reader/Dispatcher.
## for monkey test
cherrypick frameworks/native 623c43ade3225901fd6ca8dad51401ae53245b2b

## Fix clang static analyzer warning in libcore
cherrypick libcore 4bdd5651813b17dcd895eaac9bde911126287fa5
## Add size check in NativeConverter JNI code
cherrypick libcore fef459ae66f78b180f05942c9f659781c3822d07
## Avoid duplicate free in CharsetXcoderICU on OOME
cherrypick libcore 59b140db4c4bd7617792256cd5d52713409137bc

## libion: add 4.12+ kernel headers for forward compatibility
cherrypick system/core 89b8de2994d8bb809b2e2749154b9456ed096a8d
## libion: Adapt to new ION interface
cherrypick system/core 30313f8bc08b60c32c1ee0cbca20186b11bb4c0a

##################################################################
## required by X15, but are common changes from upstream
##################################################################
## wificond.rc: Set CAP_NET_RAW and CAP_NET_ADMIN explicitly rather then implictly via group
## http://git.ti.com/android/system-connectivity-wificond/commit/309d5db54abc76c53770f3e3307dadeb666e1344
cherrypick system/connectivity/wificond e823b5b106df057990cbc84255ae52919032221d

## libdrm_platform is now libdrm
## http://git.ti.com/android/platform-bootable-recovery/commit/2e2211cf5610361fb6923bdee9a86497e3c3d392
## curl_am http://git.ti.com/android/platform-bootable-recovery/commit/2e2211cf5610361fb6923bdee9a86497e3c3d392?format=patch bootable/recovery
cherrypick bootable/recovery 2ee9266827ac72bc046995f3d5318643ebc09752

## Use -Werror in external/libdrm
## http://git.ti.com/android/external-libdrm/commit/5e1df2e20c4ff858ff8eb9e20b2eba88dd8a97db
## curl_am http://git.ti.com/android/external-libdrm/commit/5e1df2e20c4ff858ff8eb9e20b2eba88dd8a97db?format=patch external/libdrm
cherrypick external/libdrm 36def26b34cb8d7a133d8eb9bdeea00767dffbb8

## Convert to Android.bp
## http://git.ti.com/android/external-libdrm/commit/def3eb73c259cba667addec5332c2dd3fa26d340
## curl_am http://git.ti.com/android/external-libdrm/commit/def3eb73c259cba667addec5332c2dd3fa26d340?format=patch  external/libdrm
cherrypick external/libdrm fa32e29a1fe81e5472aabc65d3aa25a5af5aec55

## temp: oreo-mr1: Add kernel 4.14 info
curl_am http://git.ti.com/cgit/cgit.cgi/android/platform-hardware-interfaces.git/patch/?id=ce354ad4fd8c76cc96b32de66cddc86e096e47ab hardware/interfaces
## assemble_vintf: allow <kernel> entries from source files.
cherrypick system/libvintf 8bda9c5ad4dfaa37c9de9bc144fa059d304434e6
## Compat if POLICYVERS <= security_policyvers()
cherrypick system/libvintf 9893552f4395296e509ce0d006b32593cb748d69
## ueventd: Add dynamic kernel module loading
## https://android.googlesource.com/platform/system/core/+/9963847419f41c76ca008cf0c09e986c79f04e4c%5E%21/
## http://git.ti.com/cgit/cgit.cgi/android/platform-system-core.git/patch/?id=2c31e666eef96d1dd9b093e160f1213eadad1845
curl_am http://git.ti.com/cgit/cgit.cgi/android/platform-system-core.git/patch/?id=2c31e666eef96d1dd9b093e160f1213eadad1845 system/core