#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################

##################################################
################ Backport ########################
##################################################
## fix android build error and xtest failures on optee-test projec
## based on the tag 2.4.0
if [ -d "${AOSP}/external/optee_test" ]; then
    ## Renumber regression suite tests 10xxxx and 20xxxx
    ## https://github.com/OP-TEE/optee_test/commit/cd0186b3bf0698affa09245f855dce3254858322
    cherrypick external/optee_test cd0186b3bf0698affa09245f855dce3254858322

    ## adbg_run.c: Define TAILQ_CONCAT() for aosp
    ## https://github.com/OP-TEE/optee_test/commit/f84e99672d3948714df6bf5c0d5deb1a97a2cf91
    cherrypick external/optee_test f84e99672d3948714df6bf5c0d5deb1a97a2cf91

    ## Android.mk: Rename C source files to its test suite
    ## https://github.com/OP-TEE/optee_test/commit/170a1ee60a98b407790d97dc682568981d344ca3
    cherrypick external/optee_test 170a1ee60a98b407790d97dc682568981d344ca3
fi
