#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################

##################################################
################ Backport ########################
##################################################
## fix android build error and xtest failures on optee-test projec
## based on the tag 3.1.0
if [ -d "${AOSP}/optee/optee_os" ]; then
    ## hikey: fix typo
    ## https://github.com/OP-TEE/optee_os/commit/9896cd2de525229faace23107557a74a0b48b8a0
    cherrypick optee/optee_os 9896cd2de525229faace23107557a74a0b48b8a0

    ## hikey: register additional dyn shm
    ## https://github.com/OP-TEE/optee_os/commit/8d91fe09d1f115495f09c5791fea8431e57ecab5
    cherrypick optee/optee_os 8d91fe09d1f115495f09c5791fea8431e57ecab5
fi
