#!/bin/bash

. $(dirname $0)/functions

curl_am_optee_liuyq(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local patch_url="https://github.com/liuyq/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################

##################################################
################ Backport ########################
##################################################
## fix android build error and xtest failures on optee-test projec
## based on the tag 2.4.0
if [ -d "${AOSP}/external/optee_client" ]; then
    :
fi
if [ -d "${AOSP}/external/optee_test" ]; then
    ## Android.mk: add required header files to LOCAL_ADDITIONAL_DEPENDENCIES
    curl_am_optee_liuyq optee_test de94b5164053e687c8fb1cf99311570f8536857c external/optee_test
fi
if [ -d "${AOSP}/optee/optee_os" ]; then
    ## mk/aosp_optee.mk: workaround for PHONY target limitation for AOSP master
    curl_am_optee_liuyq optee_os 4bd7ec10e0637e95ef1f6452d9cb0b3c22a60c66 optee/optee_os
fi
