#!/bin/bash

. $(dirname $0)/functions

curl_am_optee_vchong(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local patch_url="https://github.com/vchong/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################

##################################################
################ Backport ########################
##################################################
## fix android build error and xtest failures on optee-test projec
## based on the tag 2.4.0
if [ -d "${AOSP}/external/optee_client" ]; then
    :
fi
if [ -d "${AOSP}/external/optee_test" ]; then
    :
fi
if [ -d "${AOSP}/optee/optee_os" ]; then
    ## use host python command
    ## https://github.com/vchong/optee_os/commit/34ac4922e11bfe7d6721f35c348606b2f8912081
    curl_am_optee_vchong optee_os 34ac4922e11bfe7d6721f35c348606b2f8912081 optee/optee_os
fi
