#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################

##################################################
################ Backport ########################
##################################################
## CommandListener.cpp:  ensures to sort interfaces in alphabetical order
## http://android-review.linaro.org/18295
#apply --linaro system/netd 18295/2

## Workaround for wallpaper not shown correctly problem
apply --linaro frameworks/base 17696/1

## Bootchart parse command
## http://android-review.linaro.org/18203
apply --linaro system/core 18203/1

## vendor_libs: Allow btlinux service to run from vendor or system/vendor
## https://android-review.googlesource.com/c/platform/system/bt/+/657589
apply system/bt 657589/1

# Update PageTypeInfoParser to be less restrictive.
# https://android-review.googlesource.com/c/platform/frameworks/base/+/740602
cherrypick frameworks/base 93ca85a1724806c30b0fbc04837a7e869ba1c165
