#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################

##################################################
################ Backport ########################
##################################################
## CommandListener.cpp:  ensures to sort interfaces in alphabetical order
## http://android-review.linaro.org/18295
apply --linaro system/netd 18295/2

## Workaround for wallpaper not shown correctly problem
apply --linaro frameworks/base 17696/1

## Bootchart parse command
## http://android-review.linaro.org/18203
apply --linaro system/core 18203/1

## rootdir/etc/hosts: support dns resolution for loopback46.unittest.grpc.io
## http://android-review.linaro.org/17975
apply --linaro system/core 17975/2

## Track the libsparse API change.
cherrypick external/f2fs-tools 876beb2e0d312a9de2901fb0d52e2ffa06e8ea87

## libext2fs: Track the libsparse API change.
cherrypick external/e2fsprogs 019bed178935585d28cf702a8090a5598415312b
