#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Non-upstreamable ################
##################################################

##################################################
################ Backport ########################
##################################################
## CommandListener.cpp:  ensures to sort interfaces in alphabetical order
## http://android-review.linaro.org/17547
apply --linaro system/netd 17547/1

## Workaround for wallpaper not shown correctly problem
apply --linaro frameworks/base 17696/1

## Bootchart parse command
## http://android-review.linaro.org/18203
apply --linaro system/core 18203/1

## rootdir/etc/hosts: support dns resolution for loopback46.unittest.grpc.io
## http://android-review.linaro.org/17975
apply --linaro system/core 17975/2

## libdrm: Switch to Android.bp for omap driver
cherrypick external/libdrm 898243f460089111e1942b56bf0b0cee367d893e
