#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
## Patches for SWG use cases different than r-lcr #####
#######################################################
## Add optee_examples CA and TA
## http://android-review.linaro.org/17912
apply --linaro device/linaro/hikey 17912/4

## Allow extra flags for optee_os builds
## http://android-review.linaro.org/17632
apply --linaro device/linaro/hikey 17632/1

## uefi-tools: Use debug build and log level
## http://android-review.linaro.org/18328
apply --linaro device/linaro/hikey 18328/1
