#!/bin/bash

. $(dirname $0)/functions

curl_am_optee(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local user=$4
    local patch_url="https://github.com/${user}/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
## Patches for SWG use cases different than r-lcr #####
#######################################################
## Add optee_examples CA and TA
## http://android-review.linaro.org/17912
apply --linaro device/linaro/hikey 17912/4

## Allow extra flags for optee_os builds
## http://android-review.linaro.org/17632
#apply --linaro device/linaro/hikey 17632/1

## uefi-tools: Use debug build and log level
## http://android-review.linaro.org/18328
#apply --linaro device/linaro/hikey 18328/1

## fix selinux policy for optee
## https://android-review.linaro.org/#/c/19579
apply --linaro device/linaro/hikey 19579/1

## init.common.rc & sepolicy: move OPTEE related file to vendor paritition
## http://android-review.linaro.org/19518
apply --linaro device/linaro/hikey 19518/2

## KM mods - keymaster/gatekeeper patches
curl_am_optee device-linaro-hikey 33ba1801504fa2eebd1e8e8533f6ea36c70c2259 device/linaro/hikey vchong

## sepolicy/file_contexts: add entry for keymaster..
curl_am_optee device-linaro-hikey 75063fb3d92c9f585479de3ef59d4e7baff5595f device/linaro/hikey vchong
