#!/bin/bash

. $(dirname $0)/functions

curl_am_optee_vchong(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local patch_url="https://github.com/vchong/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

curl_am_optee_optee(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local patch_url="https://github.com/OP-TEE/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
## Common patches for SWG KMGK                    #####
#######################################################
## uefi-tools: disable debug build for now
#curl_am_optee_vchong device-linaro-hikey 060bcd1a959189013c66081cf43d4c97fcbbd888 device/linaro/hikey

## build default kmgk svc too
#curl_am_optee_vchong device-linaro-hikey 29723107072a56a70d48c840037660a3b6693223 device/linaro/hikey

# kmgk: add dbg prints
#curl_am_optee_vchong kmgk 36780a94 device/linaro/kmgk

# keymaster patches
cd optee/optee_os
#git fetch https://github.com/vchong/optee_os pull/1/head && git merge --no-edit FETCH_HEAD
# cherry pick instead of merge so that patches stay on top
git fetch https://github.com/vchong/optee_os kmgk_pta_rebase && git cherry-pick d66bb40a5ac74507d0257b7743ab09cd102b8343^..8c24dd6dc862415f73955f08bc7b13df222a594e
cd -
