#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
## Patches for SWG use cases different than r-lcr #####
#######################################################
## revert http://android-review.linaro.org/17597
## init rc files: enabled adb over tcpip by default
## for non-lava builds as normal users prefer adb over usb
## http://android-review.linaro.org/17625
apply --linaro device/linaro/hikey 17625/1

## Add hello world app and TA
## http://android-review.linaro.org/17629
apply --linaro device/linaro/hikey 17629/1

## Allow extra flags for optee_os builds
## http://android-review.linaro.org/17632
apply --linaro device/linaro/hikey 17632/1
