#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
## Patches for SWG use cases different than r-lcr #####
#######################################################
## Add optee_examples CA and TA
## http://android-review.linaro.org/17911
apply --linaro device/linaro/hikey 17911/1

## Allow extra flags for optee_os builds
## http://android-review.linaro.org/17632
apply --linaro device/linaro/hikey 17632/1

## revert old optee: Enable opteed in the bootloader
## before applying new one below
revert device/linaro/hikey 97dd3d5bf273e5edf6dc98f029236b2c68d68f9c

## optee: Enable opteed in the bootloader
## https://android-review.linaro.org/#/c/17488
apply --linaro device/linaro/hikey 17488/8
