#!/bin/bash

. $(dirname $0)/functions

curl_am_optee(){
    local repository=$1
    local patch_id=$2
    local patch_project="$3"
    local user=$4
    local patch_url="https://github.com/${user}/${repository}/commit/${patch_id}.patch"
    curl_am ${patch_url} ${patch_project}
}

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

#######################################################
## Patches for SWG use cases different than r-lcr #####
#######################################################
## Add optee_examples CA and TA
## http://android-review.linaro.org/17912
apply --linaro device/linaro/hikey 17912/4

## Allow extra flags for optee_os builds
## http://android-review.linaro.org/17632
#apply --linaro device/linaro/hikey 17632/1

## uefi-tools: Use debug build and log level
## http://android-review.linaro.org/18457
#apply --linaro device/linaro/hikey 18457/2

## build/tasks: add makefile to get wifi apk
## http://android-review.linaro.org/20012
apply --linaro device/linaro/hikey 20012/1

## KM mods - keymaster/gatekeeper patches
## http://android-review.linaro.org/20099
apply --linaro device/linaro/hikey 20099/1

## sepolicy/file_contexts: add entry for keymaster..
## http://android-review.linaro.org/20100
apply --linaro device/linaro/hikey 20100/7

##################################################
################ Backport ########################
##################################################
## fix android build errors for Treble
if [ -d "${AOSP}/external/optee_examples" ]; then
    :
fi
