#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ TI specific patches ################
##################################################
# Include bionic patches http://review.android.git.linaro.org/#/c/15430/ and http://review.android.git.linaro.org/#/c/15431/ http://review.android.git.linaro.org/#/c/15432/
apply --linaro bionic 15430/1
apply --linaro bionic 15431/1
apply --linaro external/tinyalsa 15432/1
apply --linaro device/ti/jacinto6evm 15468/1
apply --linaro device/ti/proprietary-open 15475/1
