#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack for LCR##############
##################################################
## workaround to include linaro tests
## http://android-review.linaro.org/c/device/ti/beagle-x15/+/20295
apply --linaro --local device/ti/beagle_x15 --remote device/ti/beagle-x15 20295/2

## workaround to build kernel and pvrsvrkm
## http://android-review.linaro.org/c/device/ti/beagle-x15/+/20294
apply --linaro --local device/ti/beagle_x15 --remote device/ti/beagle-x15 20294/2
