#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

## CommandListener.cpp:  ensures to sort interfaces in alphabetical order
## http://android-review.linaro.org/17547
apply --linaro system/netd 17547/1

## system_server: allow writing to timerslack_ns
## https://android.googlesource.com/platform/system/sepolicy/+/5c41d40ecd3558d44861374c1c490676a224b488
cherrypick system/sepolicy 5c41d40ecd3558d44861374c1c490676a224b488

## sf: Initialize DispSync in SurfaceFlinger_hwc1
## which fixed the problem of "W SurfaceFlinger: Timed out waiting for hw vsync; faking it"
## for devices when swithce to use with 8.1.0_r1
## https://android-review.googlesource.com/c/platform/frameworks/native/+/519520
cherrypick frameworks/native c9d2db18d8154ef527dbf4d34c7bb3317bbdc98c

## workaround for build 4.14 kernel and ti-uboot from source
## http://android-review.linaro.org/18130
apply --linaro  device/ti/am57xevm  18130/11

## DRM patches for TI X15
## omap: Add DRM_RDWR flag to dmabuf export
## http://git.ti.com/android/external-libdrm/commit/18a9dd97e977625b985a51475eef4a91cf49550e
curl_am http://git.ti.com/android/external-libdrm/commit/18a9dd97e977625b985a51475eef4a91cf49550e?format=patch external/libdrm
## omap: build file for android
## http://git.ti.com/android/external-libdrm/commit/0cb63a7bd7d95084eb9d280d47c02de04ee41345
curl_am http://git.ti.com/android/external-libdrm/commit/0cb63a7bd7d95084eb9d280d47c02de04ee41345?format=patch external/libdrm
## omap: install library in vendor partition
## http://git.ti.com/android/external-libdrm/commit/ea1497baa7a0462fa9a4adab8ecf1b2bf93f5d45
curl_am http://git.ti.com/android/external-libdrm/commit/ea1497baa7a0462fa9a4adab8ecf1b2bf93f5d45?format=patch external/libdrm
## omap: Convert Android.mk to Android.bp
## http://git.ti.com/android/external-libdrm/commit/077ac10b8ed77a49353de20aaae1cb52cb42c4f1
curl_am http://git.ti.com/android/external-libdrm/commit/077ac10b8ed77a49353de20aaae1cb52cb42c4f1?format=patch external/libdrm

## libdrm_platform is now libdrm
## http://git.ti.com/android/platform-bootable-recovery/commit/2e2211cf5610361fb6923bdee9a86497e3c3d392
## curl_am http://git.ti.com/android/platform-bootable-recovery/commit/2e2211cf5610361fb6923bdee9a86497e3c3d392?format=patch bootable/recovery
cherrypick bootable/recovery 2ee9266827ac72bc046995f3d5318643ebc09752

## Use -Werror in external/libdrm
## http://git.ti.com/android/external-libdrm/commit/5e1df2e20c4ff858ff8eb9e20b2eba88dd8a97db
## curl_am http://git.ti.com/android/external-libdrm/commit/5e1df2e20c4ff858ff8eb9e20b2eba88dd8a97db?format=patch external/libdrm
cherrypick external/libdrm 36def26b34cb8d7a133d8eb9bdeea00767dffbb8

## Convert to Android.bp
## http://git.ti.com/android/external-libdrm/commit/def3eb73c259cba667addec5332c2dd3fa26d340
## curl_am http://git.ti.com/android/external-libdrm/commit/def3eb73c259cba667addec5332c2dd3fa26d340?format=patch  external/libdrm
cherrypick external/libdrm fa32e29a1fe81e5472aabc65d3aa25a5af5aec55

## temp: oreo-mr1: Add kernel 4.14 info
curl_am http://git.ti.com/cgit/cgit.cgi/android/platform-hardware-interfaces.git/patch/?id=ce354ad4fd8c76cc96b32de66cddc86e096e47ab hardware/interfaces
## assemble_vintf: allow <kernel> entries from source files.
cherrypick system/libvintf 8bda9c5ad4dfaa37c9de9bc144fa059d304434e6
## Compat if POLICYVERS <= security_policyvers()
cherrypick system/libvintf 9893552f4395296e509ce0d006b32593cb748d69
## ueventd: Add dynamic kernel module loading
## https://android.googlesource.com/platform/system/core/+/9963847419f41c76ca008cf0c09e986c79f04e4c%5E%21/
## http://git.ti.com/cgit/cgit.cgi/android/platform-system-core.git/patch/?id=2c31e666eef96d1dd9b093e160f1213eadad1845
curl_am http://git.ti.com/cgit/cgit.cgi/android/platform-system-core.git/patch/?id=2c31e666eef96d1dd9b093e160f1213eadad1845 system/core