#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

######################################################
## workaround for TI projects
######################################################
## [RenderEngine] Rebind output texture when unbinding framebuffer
## https://android.googlesource.com/platform/frameworks/native/+/4dde178da6a2d1c4d3130b8319013f8f926d15f7%5E%21/
## http://android-review.linaro.org/c/platform/frameworks/native/+/21844
apply --linaro frameworks/native 21844/1
