#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack for LCR##############
##################################################
## device.mk: patch for lava test support
## http://android-review.linaro.org/18392
apply --linaro  device/ti/am57xevm  18392/1

## workaround for build 4.14 kernel and ti-uboot from source
## http://android-review.linaro.org/18130
apply --linaro  device/ti/am57xevm  18130/8
