#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

######################################################
## workaround for TI projects
######################################################
## gui: GLConsumer: Adjust crop rect as per scaling mode
## http://git.ti.com/android/frameworks-native/commit/ee5a5656bfa604fc14db7f36ddc6b6f02c5f4add
## curl_am http://git.ti.com/android/frameworks-native/commit/ee5a5656bfa604fc14db7f36ddc6b6f02c5f4add?format=patch frameworks/native
## http://android-review.linaro.org/18376
apply --linaro frameworks/native 18376/1

######################## KERNEL WORKAROUNDS#####################################
################################################################################
## workaround for PVR_K:(Error): BridgedDispatchKM: Initialisation failed.  Driver unusable.
## http://git.ti.com/cgit/cgit.cgi/ti-linux-kernel/ti-linux-kernel.git/commit/?h=ti-android-linux-4.14.y&id=16d7ceb04b554207aa68dd27c1bc11f8933813fd
#revert kernel/ti/x15 16d7ceb04b554207aa68dd27c1bc11f8933813fd
curl_am http://people.linaro.org/~yongqin.liu/patches/TI-X15-master/0001-Revert-mmap-introduce-sane-default-mmap-limits.patch kernel/ti/x15
## kernel mailing list https://www.spinics.net/lists/linux-usb/msg163049.html
## for problem reported here: https://bugs.linaro.org/show_bug.cgi?id=3866
curl_am http://people.linaro.org/~yongqin.liu/patches/TI-X15-master/EXTERNAL-tiL4.14-AND-usb-gadget-ffs-Fix-BUG-when-userland-exits-with-submitted-AIO-transfers.patch kernel/ti/x15
curl_am http://people.linaro.org/~yongqin.liu/patches/TI-X15-master/x15-vmalloc.patch kernel/ti/x15
