#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

## CommandListener.cpp:  ensures to sort interfaces in alphabetical order
## http://android-review.linaro.org/17547
apply --linaro system/netd 17547/1

## system_server: allow writing to timerslack_ns
## https://android.googlesource.com/platform/system/sepolicy/+/5c41d40ecd3558d44861374c1c490676a224b488
cherrypick system/sepolicy 5c41d40ecd3558d44861374c1c490676a224b488

## sf: Initialize DispSync in SurfaceFlinger_hwc1
## which fixed the problem of "W SurfaceFlinger: Timed out waiting for hw vsync; faking it"
## for devices when swithce to use with 8.1.0_r1
## https://android-review.googlesource.com/c/platform/frameworks/native/+/519520
cherrypick frameworks/native c9d2db18d8154ef527dbf4d34c7bb3317bbdc98c

##################################################################
## required by X15, but are common changes from upstream
##################################################################
## wificond.rc: Set CAP_NET_RAW and CAP_NET_ADMIN explicitly rather then implictly via group
## http://git.ti.com/android/system-connectivity-wificond/commit/309d5db54abc76c53770f3e3307dadeb666e1344
cherrypick system/connectivity/wificond e823b5b106df057990cbc84255ae52919032221d

## libdrm_platform is now libdrm
## http://git.ti.com/android/platform-bootable-recovery/commit/2e2211cf5610361fb6923bdee9a86497e3c3d392
## curl_am http://git.ti.com/android/platform-bootable-recovery/commit/2e2211cf5610361fb6923bdee9a86497e3c3d392?format=patch bootable/recovery
cherrypick bootable/recovery 2ee9266827ac72bc046995f3d5318643ebc09752

## Use -Werror in external/libdrm
## http://git.ti.com/android/external-libdrm/commit/5e1df2e20c4ff858ff8eb9e20b2eba88dd8a97db
## curl_am http://git.ti.com/android/external-libdrm/commit/5e1df2e20c4ff858ff8eb9e20b2eba88dd8a97db?format=patch external/libdrm
cherrypick external/libdrm 36def26b34cb8d7a133d8eb9bdeea00767dffbb8

## Convert to Android.bp
## http://git.ti.com/android/external-libdrm/commit/def3eb73c259cba667addec5332c2dd3fa26d340
## curl_am http://git.ti.com/android/external-libdrm/commit/def3eb73c259cba667addec5332c2dd3fa26d340?format=patch  external/libdrm
cherrypick external/libdrm fa32e29a1fe81e5472aabc65d3aa25a5af5aec55

## workaround for build 4.14 kernel and ti-uboot from source
## http://android-review.linaro.org/18130
apply --linaro  device/ti/am57xevm  18130/8

## Android.mk: use LOCAL_VENDOR_MODULE instead of LOCAL_MODULE_PATH
## http://android-review.linaro.org/17955
## http://android-review.linaro.org/17956
## http://android-review.linaro.org/17957
apply --linaro hardware/ti/linuxutils 17955/1
apply --linaro hardware/ti/ipc 17956/1

######################################################
## patches from TI forks
######################################################
## HACK: Run SurfaceFlinger as root to allow access to software sync file
## http://git.ti.com/android/frameworks-native/commit/5232c48f850d7dd5b68f138a25023d7cfd72826f
curl_am http://git.ti.com/android/frameworks-native/commit/5232c48f850d7dd5b68f138a25023d7cfd72826f?format=patch frameworks/native
## gui: GLConsumer: Adjust crop rect as per scaling mode
## http://git.ti.com/android/frameworks-native/commit/ee5a5656bfa604fc14db7f36ddc6b6f02c5f4add
curl_am http://git.ti.com/android/frameworks-native/commit/ee5a5656bfa604fc14db7f36ddc6b6f02c5f4add?format=patch frameworks/native

## DRM patches for TI X15
## omap: Add DRM_RDWR flag to dmabuf export
## http://git.ti.com/android/external-libdrm/commit/18a9dd97e977625b985a51475eef4a91cf49550e
curl_am http://git.ti.com/android/external-libdrm/commit/18a9dd97e977625b985a51475eef4a91cf49550e?format=patch external/libdrm
## omap: build file for android
## http://git.ti.com/android/external-libdrm/commit/0cb63a7bd7d95084eb9d280d47c02de04ee41345
curl_am http://git.ti.com/android/external-libdrm/commit/0cb63a7bd7d95084eb9d280d47c02de04ee41345?format=patch external/libdrm
## omap: install library in vendor partition
## http://git.ti.com/android/external-libdrm/commit/ea1497baa7a0462fa9a4adab8ecf1b2bf93f5d45
curl_am http://git.ti.com/android/external-libdrm/commit/ea1497baa7a0462fa9a4adab8ecf1b2bf93f5d45?format=patch external/libdrm
## omap: Convert Android.mk to Android.bp
## http://git.ti.com/android/external-libdrm/commit/077ac10b8ed77a49353de20aaae1cb52cb42c4f1
curl_am http://git.ti.com/android/external-libdrm/commit/077ac10b8ed77a49353de20aaae1cb52cb42c4f1?format=patch external/libdrm
