#!/bin/sh

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack   ###################
##################################################
## DRM patches for TI X15
## https://android-review.linaro.org/#/c/17278
## https://android-review.linaro.org/#/c/17279
## https://android-review.linaro.org/#/c/17280
## https://android-review.linaro.org/#/c/17281
apply --linaro external/libdrm 17278/1
apply --linaro external/libdrm 17279/1
apply --linaro external/libdrm 17280/1
apply --linaro external/libdrm 17281/1

## patch to inherit linaro common-device.mk
## mainly for support lava test
## https://android-review.linaro.org/#/c/17304/
apply --linaro  device/ti/am57xevm  17304/1
