#!/bin/bash

. $(dirname $0)/functions

PATCHES=0
if [ -n "$1" ]; then
        AOSP="$1"
else
        AOSP="`pwd`"
fi

if ! [ -d "$AOSP" ] && ! [ -d "$AOSP/bionic" ] && [ -d "$AOSP"/build ]; then
        echo "This script must be run from the AOSP source directory"
        echo "or with the AOSP source directory as its first parameter."
        exit 1
fi

##################################################
################ Linaro hack   ###################
##################################################
## workaround to include linaro tests
## https://android-review.linaro.org/#/c/device/ti/beagle-x15/+/20334/
apply --linaro --local device/ti/beagle_x15 --remote device/ti/beagle-x15 20334/1

## workaround to build kernel and pvrsvrkm
## http://android-review.linaro.org/c/device/ti/beagle-x15/+/20314
apply --linaro --local device/ti/beagle_x15 --remote device/ti/beagle-x15 20314/4

######################################################
## patches from TI forks
######################################################
## temp: compatibility_matrices: added 4.19 kernel support
## http://git.ti.com/android/platform-hardware-interfaces/commit/4b03e692d337eafd0b1254bd30fa235f103409a2
curl_am http://git.ti.com/android/platform-hardware-interfaces/commit/4b03e692d337eafd0b1254bd30fa235f103409a2?format=patch hardware/interfaces

## Patch from AOSP master for mkimage
## http://android-review.linaro.org/c/platform/external/u-boot/+/20340
apply --linaro external/u-boot 20340/1
